# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "addr-to-ip-port-1.5.1" = {
      name = "addr-to-ip-port";
      packageName = "addr-to-ip-port";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/addr-to-ip-port/-/addr-to-ip-port-1.5.1.tgz";
        sha512 = "bA+dyydTNuQtrEDJ0g9eR7XabNhvrM5yZY0hvTbNK3yvoeC73ZqMES6E1cEqH9WPxs4uMtMsOjfwS4FmluhsAA==";
      };
    };
    "ansi-regex-5.0.0" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-5.0.0.tgz";
        sha512 = "bY6fj56OUQ0hU1KjFNDQuJFezqKdrAyFdIevADiqrWHwSlbmBNMHp5ak2f40Pm8JTFyM2mqxkG6ngkHO11f/lg==";
      };
    };
    "ansi-styles-4.3.0" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-4.3.0.tgz";
        sha512 = "zbB9rCJAT1rbjiVDb2hqKFHNYLxgtk8NURxZ3IZwD3F6NtxbXZQCnnSi1Lkx+IDohdPlFp222wVALIheZJQSEg==";
      };
    };
    "balanced-match-1.0.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.2.tgz";
        sha512 = "3oSeUO0TMV67hN1AmbXsK4yaqU7tjiHlbxRDZOpH0KW9+CeX4bRAaX0Anxt0tx2MrpRpWwQaPwIlISEJhYU5Pw==";
      };
    };
    "base64-js-1.5.1" = {
      name = "base64-js";
      packageName = "base64-js";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64-js/-/base64-js-1.5.1.tgz";
        sha512 = "AKpaYlHn8t4SVbOHCy+b5+KKgvR4vrsD8vbvrbiQJps7fKDTkjkDry6ji0rUJjC0kzbNePLwzxq8iypo41qeWA==";
      };
    };
    "bencode-2.0.1" = {
      name = "bencode";
      packageName = "bencode";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bencode/-/bencode-2.0.1.tgz";
        sha512 = "2uhEl8FdjSBUyb69qDTgOEeeqDTa+n3yMQzLW0cOzNf1Ow5bwcg3idf+qsWisIKRH8Bk8oC7UXL8irRcPA8ZEQ==";
      };
    };
    "bep53-range-1.1.0" = {
      name = "bep53-range";
      packageName = "bep53-range";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bep53-range/-/bep53-range-1.1.0.tgz";
        sha512 = "yGQTG4NtwTciX0Bkgk1FqQL4p+NiCQKpTSFho2lrxvUkXIlzyJDwraj8aYxAxRZMnnOhRr7QlIBoMRPEnIR34Q==";
      };
    };
    "binary-search-1.3.6" = {
      name = "binary-search";
      packageName = "binary-search";
      version = "1.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/binary-search/-/binary-search-1.3.6.tgz";
        sha512 = "nbE1WxOTTrUWIfsfZ4aHGYu5DOuNkbxGokjV6Z2kxfJK3uaAb8zNK1muzOeipoLHZjInT4Br88BHpzevc681xA==";
      };
    };
    "bitfield-4.0.0" = {
      name = "bitfield";
      packageName = "bitfield";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bitfield/-/bitfield-4.0.0.tgz";
        sha512 = "jtuSG9CQr5yoHFuvhgf50+DH8Aezl3C/mMSfqdG4DqP7Kqe34uBUtCEHPN9oWaldTm96/i7y5e778SnM5ES4rw==";
      };
    };
    "bittorrent-dht-10.0.0" = {
      name = "bittorrent-dht";
      packageName = "bittorrent-dht";
      version = "10.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bittorrent-dht/-/bittorrent-dht-10.0.0.tgz";
        sha512 = "mrM18HMabvd3n/hQa4PYe942nWvBsJCBQb5PfT9kUJLlspNPGiulZYSCgWs7+XarS7nufYrGEp07f9eKTKIrgw==";
      };
    };
    "bittorrent-lsd-1.1.0" = {
      name = "bittorrent-lsd";
      packageName = "bittorrent-lsd";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bittorrent-lsd/-/bittorrent-lsd-1.1.0.tgz";
        sha512 = "j9F+bDt1R//+kLfeSgkmc1A3x0u70gjb/FXaRgTtw+V3wIeYjOekiIlmsXf1SNKuxU5YHDkNL8CFNHx+MfSPSw==";
      };
    };
    "bittorrent-peerid-1.3.3" = {
      name = "bittorrent-peerid";
      packageName = "bittorrent-peerid";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/bittorrent-peerid/-/bittorrent-peerid-1.3.3.tgz";
        sha512 = "tSh9HdQgwyEAfo1jzoGEis6o/zs4CcdRTchG93XVl5jct+DCAN90M5MVUV76k2vJ9Xg3GAzLB5NLsY/vnVTh6w==";
      };
    };
    "bittorrent-protocol-3.4.2" = {
      name = "bittorrent-protocol";
      packageName = "bittorrent-protocol";
      version = "3.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bittorrent-protocol/-/bittorrent-protocol-3.4.2.tgz";
        sha512 = "a7ueJzmCImWIXfKrJ+dT6mgqi5+LFByAXoMXhV/cYt/y8kplaC8N9ZWfpiTidJY4H2o1GTsyMy73o62a/rZ0Ow==";
      };
    };
    "bittorrent-tracker-9.17.3" = {
      name = "bittorrent-tracker";
      packageName = "bittorrent-tracker";
      version = "9.17.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/bittorrent-tracker/-/bittorrent-tracker-9.17.3.tgz";
        sha512 = "Z37yunPPT8pIEkB0Q0bDP1fMke2Rez7JSsmqwqGKoJWh4zjAtFgrEw2GHYNllRRvcy+fkfVPWt7ArvxsGoUmfA==";
      };
    };
    "blob-to-buffer-1.2.9" = {
      name = "blob-to-buffer";
      packageName = "blob-to-buffer";
      version = "1.2.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/blob-to-buffer/-/blob-to-buffer-1.2.9.tgz";
        sha512 = "BF033y5fN6OCofD3vgHmNtwZWRcq9NLyyxyILx9hfMy1sXYy4ojFl765hJ2lP0YaN2fuxPaLO2Vzzoxy0FLFFA==";
      };
    };
    "block-stream2-2.1.0" = {
      name = "block-stream2";
      packageName = "block-stream2";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/block-stream2/-/block-stream2-2.1.0.tgz";
        sha512 = "suhjmLI57Ewpmq00qaygS8UgEq2ly2PCItenIyhMqVjo4t4pGzqMvfgJuX8iWTeSDdfSSqS6j38fL4ToNL7Pfg==";
      };
    };
    "bn.js-5.2.0" = {
      name = "bn.js";
      packageName = "bn.js";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bn.js/-/bn.js-5.2.0.tgz";
        sha512 = "D7iWRBvnZE8ecXiLj/9wbxH7Tk79fAh8IHaTNq1RWRixsS02W+5qS+iE9yq6RYl0asXx5tw0bLhmT5pIfbSquw==";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "browserify-package-json-1.0.1" = {
      name = "browserify-package-json";
      packageName = "browserify-package-json";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-package-json/-/browserify-package-json-1.0.1.tgz";
        sha1 = "98dde8aa5c561fd6d3fe49bbaa102b74b396fdea";
      };
    };
    "buffer-6.0.3" = {
      name = "buffer";
      packageName = "buffer";
      version = "6.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer/-/buffer-6.0.3.tgz";
        sha512 = "FTiCpNxtwiZZHEZbcbTIcZjERVICn9yq/pDFkTl95/AxzD1naBctN7YO68riM/gLSDY7sdrMby8hofADYuuqOA==";
      };
    };
    "buffer-alloc-1.2.0" = {
      name = "buffer-alloc";
      packageName = "buffer-alloc";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-alloc/-/buffer-alloc-1.2.0.tgz";
        sha512 = "CFsHQgjtW1UChdXgbyJGtnm+O/uLQeZdtbDo8mfUgYXCHSM1wgrVxXm6bSyrUuErEb+4sYVGCzASBRot7zyrow==";
      };
    };
    "buffer-alloc-unsafe-1.1.0" = {
      name = "buffer-alloc-unsafe";
      packageName = "buffer-alloc-unsafe";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-alloc-unsafe/-/buffer-alloc-unsafe-1.1.0.tgz";
        sha512 = "TEM2iMIEQdJ2yjPJoSIsldnleVaAk1oW3DBVUykyOLsEsFmEc9kn+SFFPz+gl54KQNxlDnAwCXosOS9Okx2xAg==";
      };
    };
    "buffer-fill-1.0.0" = {
      name = "buffer-fill";
      packageName = "buffer-fill";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-fill/-/buffer-fill-1.0.0.tgz";
        sha1 = "f8f78b76789888ef39f205cd637f68e702122b2c";
      };
    };
    "buffer-from-1.1.1" = {
      name = "buffer-from";
      packageName = "buffer-from";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-from/-/buffer-from-1.1.1.tgz";
        sha512 = "MQcXEUbCKtEo7bhqEs6560Hyd4XaovZlO/k9V3hjVUF/zwW7KBVdSK4gIt/bzwS9MbR5qob+F5jusZsb0YQK2A==";
      };
    };
    "cache-chunk-store-3.2.2" = {
      name = "cache-chunk-store";
      packageName = "cache-chunk-store";
      version = "3.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/cache-chunk-store/-/cache-chunk-store-3.2.2.tgz";
        sha512 = "2lJdWbgHFFxcSth9s2wpId3CR3v1YC63KjP4T9WhpW7LWlY7Hiiei3QwwqzkWqlJTfR8lSy9F5kRQECeyj+yQA==";
      };
    };
    "chalk-4.1.1" = {
      name = "chalk";
      packageName = "chalk";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-4.1.1.tgz";
        sha512 = "diHzdDKxcU+bAsUboHLPEDQiw0qEe0qd7SYUn3HgcFlWgbDcfLGswOHYeGrHKzG9z6UYf01d9VFMfZxPM1xZSg==";
      };
    };
    "charset-1.0.1" = {
      name = "charset";
      packageName = "charset";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/charset/-/charset-1.0.1.tgz";
        sha512 = "6dVyOOYjpfFcL1Y4qChrAoQLRHvj2ziyhcm0QJlhOcAhykL/k1kTUPbeo+87MNRTRdk2OIIsIXbuF3x2wi5EXg==";
      };
    };
    "chrome-dgram-3.0.6" = {
      name = "chrome-dgram";
      packageName = "chrome-dgram";
      version = "3.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/chrome-dgram/-/chrome-dgram-3.0.6.tgz";
        sha512 = "bqBsUuaOiXiqxXt/zA/jukNJJ4oaOtc7ciwqJpZVEaaXwwxqgI2/ZdG02vXYWUhHGziDlvGMQWk0qObgJwVYKA==";
      };
    };
    "chrome-dns-1.0.1" = {
      name = "chrome-dns";
      packageName = "chrome-dns";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/chrome-dns/-/chrome-dns-1.0.1.tgz";
        sha512 = "HqsYJgIc8ljJJOqOzLphjAs79EUuWSX3nzZi2LNkzlw3GIzAeZbaSektC8iT/tKvLqZq8yl1GJu5o6doA4TRbg==";
      };
    };
    "chrome-net-3.3.4" = {
      name = "chrome-net";
      packageName = "chrome-net";
      version = "3.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/chrome-net/-/chrome-net-3.3.4.tgz";
        sha512 = "Jzy2EnzmE+ligqIZUsmWnck9RBXLuUy6CaKyuNMtowFG3ZvLt8d+WBJCTPEludV0DHpIKjAOlwjFmTaEdfdWCw==";
      };
    };
    "chunk-store-stream-4.3.0" = {
      name = "chunk-store-stream";
      packageName = "chunk-store-stream";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/chunk-store-stream/-/chunk-store-stream-4.3.0.tgz";
        sha512 = "qby+/RXoiMoTVtPiylWZt7KFF1jy6M829TzMi2hxZtBIH9ptV19wxcft6zGiXLokJgCbuZPGNGab6DWHqiSEKw==";
      };
    };
    "cliui-7.0.4" = {
      name = "cliui";
      packageName = "cliui";
      version = "7.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/cliui/-/cliui-7.0.4.tgz";
        sha512 = "OcRE68cOsVMXp1Yvonl/fzkQOyjLSu/8bhPDfQt0e0/Eb283TKP20Fs2MqoPsr9SwA595rRCA+QMzYc9nBP+JQ==";
      };
    };
    "color-convert-2.0.1" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-2.0.1.tgz";
        sha512 = "RRECPsj7iu/xb5oKYcsFHSppFNnsj/52OVTRKb4zP5onXwVF3zVmmToNcOfGC+CRDpfK/U584fMg38ZHCaElKQ==";
      };
    };
    "color-name-1.1.4" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.4.tgz";
        sha512 = "dOy+3AuW3a2wNbZHIuMZpTcgjGuLU/uBL/ubcZF9OXbDo8ff4O8yVp5Bf0efS8uEoYo5q4Fx7dY9OgQGXgAsQA==";
      };
    };
    "common-tags-1.8.0" = {
      name = "common-tags";
      packageName = "common-tags";
      version = "1.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/common-tags/-/common-tags-1.8.0.tgz";
        sha512 = "6P6g0uetGpW/sdyUy/iQQCbFF0kWVMSIVSyYz7Zgjcgh8mgw8PQzDNZeyZ5DQ2gM7LBoZPHmnjz8rUthkBG5tw==";
      };
    };
    "compact2string-1.4.1" = {
      name = "compact2string";
      packageName = "compact2string";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/compact2string/-/compact2string-1.4.1.tgz";
        sha512 = "3D+EY5nsRhqnOwDxveBv5T8wGo4DEvYxjDtPGmdOX+gfr5gE92c2RC0w2wa+xEefm07QuVqqcF3nZJUZ92l/og==";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "concat-stream-1.6.2" = {
      name = "concat-stream";
      packageName = "concat-stream";
      version = "1.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-stream/-/concat-stream-1.6.2.tgz";
        sha512 = "27HBghJxjiZtIk3Ycvn/4kbJk/1uZuJFfuPEns6LaEvpvG1f0hTea8lilrouyo9mVc2GWdcEZ8OLoGmSADlrCw==";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "cpus-1.0.3" = {
      name = "cpus";
      packageName = "cpus";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/cpus/-/cpus-1.0.3.tgz";
        sha512 = "PXHBvGLuL69u55IkLa5e5838fLhIMHxmkV4ge42a8alGyn7BtawYgI0hQ849EedvtHIOLNNH3i6eQU1BiE9SUA==";
      };
    };
    "create-torrent-4.7.0" = {
      name = "create-torrent";
      packageName = "create-torrent";
      version = "4.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/create-torrent/-/create-torrent-4.7.0.tgz";
        sha512 = "Pb3XjZNKdCs0Nk46yFKb82y+a3xRQeMvGi1AlJfIV40y/iwkgBqzS5EfqdnakEOvh2jzTOx3v8QxZpkz4hPzyw==";
      };
    };
    "debug-2.6.9" = {
      name = "debug";
      packageName = "debug";
      version = "2.6.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.6.9.tgz";
        sha512 = "bC7ElrdJaJnPbAP+1EotYvqZsb3ecl5wi6Bfi6BJTUcNowp6cvspg0jXznRTKDjm/E7AdgFBVeAPVMNcKGsHMA==";
      };
    };
    "debug-4.3.2" = {
      name = "debug";
      packageName = "debug";
      version = "4.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.3.2.tgz";
        sha512 = "mOp8wKcvj7XxC78zLgw/ZA+6TSgkoE2C/ienthhRD298T7UNwAg9diBpLRxC0mOezLl4B0xV7M0cCO6P/O0Xhw==";
      };
    };
    "decompress-response-3.3.0" = {
      name = "decompress-response";
      packageName = "decompress-response";
      version = "3.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/decompress-response/-/decompress-response-3.3.0.tgz";
        sha1 = "80a4dd323748384bfa248083622aedec982adff3";
      };
    };
    "decompress-response-6.0.0" = {
      name = "decompress-response";
      packageName = "decompress-response";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/decompress-response/-/decompress-response-6.0.0.tgz";
        sha512 = "aW35yZM6Bb/4oJlZncMH2LCoZtJXTRxES17vE3hoRiowU2kWHaJKFkSBDnDR+cm9J+9QhXmREyIfv0pji9ejCQ==";
      };
    };
    "define-lazy-prop-2.0.0" = {
      name = "define-lazy-prop";
      packageName = "define-lazy-prop";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/define-lazy-prop/-/define-lazy-prop-2.0.0.tgz";
        sha512 = "Ds09qNh8yw3khSjiJjiUInaGX9xlqZDY7JVryGxdxV7NPeuqQfplOpQ66yJFZut3jLa5zOwkXw1g9EI2uKh4Og==";
      };
    };
    "dlnacasts-0.1.0" = {
      name = "dlnacasts";
      packageName = "dlnacasts";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dlnacasts/-/dlnacasts-0.1.0.tgz";
        sha1 = "f805211dcac74f6bb3a4d5d5541ad783b1b67d22";
      };
    };
    "ecstatic-4.1.4" = {
      name = "ecstatic";
      packageName = "ecstatic";
      version = "4.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/ecstatic/-/ecstatic-4.1.4.tgz";
        sha512 = "8E4ZLK4uRuB9pwywGpy/B9vcz4gCp6IY7u4cMbeCINr/fjb1v+0wf0Ae2XlfSnG8xZYnE4uaJBjFkYI0bqcIdw==";
      };
    };
    "ee-first-1.1.1" = {
      name = "ee-first";
      packageName = "ee-first";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ee-first/-/ee-first-1.1.1.tgz";
        sha1 = "590c61156b0ae2f4f0255732a158b266bc56b21d";
      };
    };
    "elementtree-0.1.7" = {
      name = "elementtree";
      packageName = "elementtree";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/elementtree/-/elementtree-0.1.7.tgz";
        sha1 = "9ac91be6e52fb6e6244c4e54a4ac3ed8ae8e29c0";
      };
    };
    "emoji-regex-8.0.0" = {
      name = "emoji-regex";
      packageName = "emoji-regex";
      version = "8.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/emoji-regex/-/emoji-regex-8.0.0.tgz";
        sha512 = "MSjYzcWNOA0ewAHpz0MxpYFvwg6yjy1NG3xteoqz644VCo/RPgnr1/GGt+ic3iJTzQ8Eu3TdM14SawnVUmGE6A==";
      };
    };
    "end-of-stream-1.4.4" = {
      name = "end-of-stream";
      packageName = "end-of-stream";
      version = "1.4.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/end-of-stream/-/end-of-stream-1.4.4.tgz";
        sha512 = "+uw1inIHVPQoaVuHzRyXd21icM+cnt4CzD5rW+NC1wjOUSTOs+Te7FOv7AhN7vS9x/oIyhLP5PR1H+phQAHu5Q==";
      };
    };
    "err-code-3.0.1" = {
      name = "err-code";
      packageName = "err-code";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/err-code/-/err-code-3.0.1.tgz";
        sha512 = "GiaH0KJUewYok+eeY05IIgjtAe4Yltygk9Wqp1V5yVWLdhf0hYZchRjNIT9bb0mSwRcIusT3cx7PJUf3zEIfUA==";
      };
    };
    "escalade-3.1.1" = {
      name = "escalade";
      packageName = "escalade";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/escalade/-/escalade-3.1.1.tgz";
        sha512 = "k0er2gUkLf8O0zKJiAhmkTnJlTvINGv7ygDNPbeIsX/TJjGJZHuh9B2UxbsaEkmlEo9MfhrSzmhIlhRlI2GXnw==";
      };
    };
    "escape-html-1.0.3" = {
      name = "escape-html";
      packageName = "escape-html";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-html/-/escape-html-1.0.3.tgz";
        sha1 = "0258eae4d3d0c0974de1c169188ef0051d1d1988";
      };
    };
    "executable-4.1.1" = {
      name = "executable";
      packageName = "executable";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/executable/-/executable-4.1.1.tgz";
        sha512 = "8iA79xD3uAch729dUG8xaaBBFGaEa0wdD2VkYLFHwlqosEj/jT66AzcreRDSgV7ehnNLBW2WR5jIXwGKjVdTLg==";
      };
    };
    "filestream-5.0.0" = {
      name = "filestream";
      packageName = "filestream";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/filestream/-/filestream-5.0.0.tgz";
        sha512 = "5H3RqSaJp12THfZiNWodYM7TiKfQvrpX+EIOrB1XvCceTys4yvfEIl8wDp+/yI8qj6Bxym8m0NYWwVXDAet/+A==";
      };
    };
    "freelist-1.0.3" = {
      name = "freelist";
      packageName = "freelist";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/freelist/-/freelist-1.0.3.tgz";
        sha1 = "006775509f3935701784d3ed2fc9f12c9df1bab2";
      };
    };
    "fs-chunk-store-2.0.3" = {
      name = "fs-chunk-store";
      packageName = "fs-chunk-store";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs-chunk-store/-/fs-chunk-store-2.0.3.tgz";
        sha512 = "qQi93nHX3880gtoQPt1hKQcuYBNVfCbMk8OVRDqR0cJ0riheELW25ry9yl7pII8E9gOAONTGKBD5N/zGHFSVQg==";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "get-browser-rtc-1.1.0" = {
      name = "get-browser-rtc";
      packageName = "get-browser-rtc";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-browser-rtc/-/get-browser-rtc-1.1.0.tgz";
        sha512 = "MghbMJ61EJrRsDe7w1Bvqt3ZsBuqhce5nrn/XAwgwOXhcsz53/ltdxOse1h/8eKXj5slzxdsz56g5rzOFSGwfQ==";
      };
    };
    "get-caller-file-2.0.5" = {
      name = "get-caller-file";
      packageName = "get-caller-file";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-caller-file/-/get-caller-file-2.0.5.tgz";
        sha512 = "DyFP3BM/3YHTQOCUL/w0OZHR0lpKeGrxotcHWcqNEdnltqFwXVfhEBQ94eIo34AfQpo0rGki4cyIiftY06h2Fg==";
      };
    };
    "get-stdin-8.0.0" = {
      name = "get-stdin";
      packageName = "get-stdin";
      version = "8.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-stdin/-/get-stdin-8.0.0.tgz";
        sha512 = "sY22aA6xchAzprjyqmSEQv4UbAAzRN0L2dQB0NlN5acTTK9Don6nhoc3eAbUnpZiCANAMfd/+40kVdKfFygohg==";
      };
    };
    "glob-7.1.7" = {
      name = "glob";
      packageName = "glob";
      version = "7.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.1.7.tgz";
        sha512 = "OvD9ENzPLbegENnYP5UUfJIirTg4+XwMWGaQfQTY0JenxNvvIKP3U3/tAQSPIu/lHxXYSZmpXlUHeqAIdKzBLQ==";
      };
    };
    "has-flag-4.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-4.0.0.tgz";
        sha512 = "EykJT/Q1KjTWctppgIAgfSO0tKVuZUjhgMr17kqTumMl6Afv3EISleU7qZUzoXDFTAHTDC4NOoG/ZxU3EvlMPQ==";
      };
    };
    "he-1.2.0" = {
      name = "he";
      packageName = "he";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/he/-/he-1.2.0.tgz";
        sha512 = "F/1DnUGPopORZi0ni+CvrCgHQ5FyEAHRLSApuYWMmrbSwoN2Mn/7k+Gl38gJnR7yyDZk6WLXwiGod1JOWNDKGw==";
      };
    };
    "http-node-git://github.com/feross/http-node#webtorrent" = {
      name = "http-node";
      packageName = "http-node";
      version = "1.2.0";
      src = fetchgit {
        url = "git://github.com/feross/http-node";
        rev = "342ef8624495343ffd050bd0808b3750cf0e3974";
        sha256 = "d7408d01b05fcbd5bb4fb44fd3d7d71463bafd5124d7e69c6f3e97cef8c65368";
      };
    };
    "http-parser-js-0.4.13" = {
      name = "http-parser-js";
      packageName = "http-parser-js";
      version = "0.4.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-parser-js/-/http-parser-js-0.4.13.tgz";
        sha1 = "3bd6d6fde6e3172c9334c3b33b6c193d80fe1137";
      };
    };
    "ieee754-1.2.1" = {
      name = "ieee754";
      packageName = "ieee754";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ieee754/-/ieee754-1.2.1.tgz";
        sha512 = "dcyqhDvX1C46lXZcVqCpK+FtMRQVdIMN6/Df5js2zouUsqG7I6sFxitIC+7KYK29KdXOLHdu9zL4sFnoVQnqaA==";
      };
    };
    "immediate-chunk-store-2.2.0" = {
      name = "immediate-chunk-store";
      packageName = "immediate-chunk-store";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/immediate-chunk-store/-/immediate-chunk-store-2.2.0.tgz";
        sha512 = "1bHBna0hCa6arRXicu91IiL9RvvkbNYLVq+mzWdaLGZC3hXvX4doh8e1dLhMKez5siu63CYgO5NrGJbRX5lbPA==";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "ip-1.1.5" = {
      name = "ip";
      packageName = "ip";
      version = "1.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/ip/-/ip-1.1.5.tgz";
        sha1 = "bdded70114290828c0a039e72ef25f5aaec4354a";
      };
    };
    "ip-set-2.1.0" = {
      name = "ip-set";
      packageName = "ip-set";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ip-set/-/ip-set-2.1.0.tgz";
        sha512 = "JdHz4tSMx1IeFj8yEcQU0i58qiSkOlmZXkZ8+HJ0ROV5KcgLRDO9F703oJ1GeZCvqggrcCbmagD/V7hghY62wA==";
      };
    };
    "ipaddr.js-1.9.1" = {
      name = "ipaddr.js";
      packageName = "ipaddr.js";
      version = "1.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ipaddr.js/-/ipaddr.js-1.9.1.tgz";
        sha512 = "0KI/607xoxSToH7GjN1FfSbLoU0+btTicjsQSWQlh/hZykN8KpmMf7uYwPW3R+akZ6R/w18ZlXSHBYXiYUPO3g==";
      };
    };
    "ipaddr.js-2.0.1" = {
      name = "ipaddr.js";
      packageName = "ipaddr.js";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ipaddr.js/-/ipaddr.js-2.0.1.tgz";
        sha512 = "1qTgH9NG+IIJ4yfKs2e6Pp1bZg8wbDbKHT21HrLIeYBTRLgMYKnMTPAuI3Lcs61nfx5h1xlXnbJtH1kX5/d/ng==";
      };
    };
    "is-ascii-1.0.0" = {
      name = "is-ascii";
      packageName = "is-ascii";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-ascii/-/is-ascii-1.0.0.tgz";
        sha1 = "f02ad0259a0921cd199ff21ce1b09e0f6b4e3929";
      };
    };
    "is-docker-2.2.1" = {
      name = "is-docker";
      packageName = "is-docker";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-docker/-/is-docker-2.2.1.tgz";
        sha512 = "F+i2BKsFrH66iaUFc0woD8sLy8getkwTwtOBjvs56Cx4CgJDeKQeqfz8wAYiSb8JOprWhHH5p77PbmYCvvUuXQ==";
      };
    };
    "is-file-1.0.0" = {
      name = "is-file";
      packageName = "is-file";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-file/-/is-file-1.0.0.tgz";
        sha1 = "28a44cfbd9d3db193045f22b65fce8edf9620596";
      };
    };
    "is-fullwidth-code-point-3.0.0" = {
      name = "is-fullwidth-code-point";
      packageName = "is-fullwidth-code-point";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-3.0.0.tgz";
        sha512 = "zymm5+u+sCsSWyD9qNaejV3DFvhCKclKdizYaJUuHA83RLjb7nSuGnddCHGv0hk+KY7BMAlsWeK4Ueg6EV6XQg==";
      };
    };
    "is-typedarray-1.0.0" = {
      name = "is-typedarray";
      packageName = "is-typedarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-typedarray/-/is-typedarray-1.0.0.tgz";
        sha1 = "e479c80858df0c1b11ddda6940f96011fcda4a9a";
      };
    };
    "is-wsl-2.2.0" = {
      name = "is-wsl";
      packageName = "is-wsl";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-wsl/-/is-wsl-2.2.0.tgz";
        sha512 = "fKzAra0rGJUUBwGBgNkHZuToZcn+TtXHpeCgmkMJMMYx1sQDYaCSyjJBSCa2nH1DGm7s3n1oBnohoVTBaN7Lww==";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha1 = "bb935d48582cba168c06834957a54a3e07124f11";
      };
    };
    "junk-3.1.0" = {
      name = "junk";
      packageName = "junk";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/junk/-/junk-3.1.0.tgz";
        sha512 = "pBxcB3LFc8QVgdggvZWyeys+hnrNWg4OcZIU/1X59k5jQdLBlCsYGRQaz234SqoRLTCgMH00fY0xRJH+F9METQ==";
      };
    };
    "k-bucket-5.1.0" = {
      name = "k-bucket";
      packageName = "k-bucket";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/k-bucket/-/k-bucket-5.1.0.tgz";
        sha512 = "Fac7iINEovXIWU20GPnOMLUbjctiS+cnmyjC4zAUgvs3XPf1vo9akfCHkigftSic/jiKqKl+KA3a/vFcJbHyCg==";
      };
    };
    "k-rpc-5.1.0" = {
      name = "k-rpc";
      packageName = "k-rpc";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/k-rpc/-/k-rpc-5.1.0.tgz";
        sha512 = "FGc+n70Hcjoa/X2JTwP+jMIOpBz+pkRffHnSl9yrYiwUxg3FIgD50+u1ePfJUOnRCnx6pbjmVk5aAeB1wIijuQ==";
      };
    };
    "k-rpc-socket-1.11.1" = {
      name = "k-rpc-socket";
      packageName = "k-rpc-socket";
      version = "1.11.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/k-rpc-socket/-/k-rpc-socket-1.11.1.tgz";
        sha512 = "8xtA8oqbZ6v1Niryp2/g4GxW16EQh5MvrUylQoOG+zcrDff5CKttON2XUXvMwlIHq4/2zfPVFiinAccJ+WhxoA==";
      };
    };
    "last-one-wins-1.0.4" = {
      name = "last-one-wins";
      packageName = "last-one-wins";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/last-one-wins/-/last-one-wins-1.0.4.tgz";
        sha1 = "c1bfd0cbcb46790ec9156b8d1aee8fcb86cda22a";
      };
    };
    "load-ip-set-2.2.1" = {
      name = "load-ip-set";
      packageName = "load-ip-set";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/load-ip-set/-/load-ip-set-2.2.1.tgz";
        sha512 = "G3hQXehU2LTOp52e+lPffpK4EvidfjwbvHaGqmFcp4ptiZagR4xFdL+D08kMX906dxeqZyWhfonEjdUxrWcldg==";
      };
    };
    "lru-3.1.0" = {
      name = "lru";
      packageName = "lru";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru/-/lru-3.1.0.tgz";
        sha1 = "ea7fb8546d83733396a13091d76cfeb4c06837d5";
      };
    };
    "lt_donthave-1.0.1" = {
      name = "lt_donthave";
      packageName = "lt_donthave";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lt_donthave/-/lt_donthave-1.0.1.tgz";
        sha512 = "PfOXfDN9GnUjlNHjjxKQuMxPC8s12iSrnmg+Ff1BU1uLn7S1BFAKzpZCu6Gwg3WsCUvTZrZoDSHvy6B/j+N4/Q==";
      };
    };
    "magnet-uri-6.2.0" = {
      name = "magnet-uri";
      packageName = "magnet-uri";
      version = "6.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/magnet-uri/-/magnet-uri-6.2.0.tgz";
        sha512 = "O9AgdDwT771fnUj0giPYu/rACpz8173y8UXCSOdLITjOVfBenZ9H9q3FqQmveK+ORUMuD+BkKNSZP8C3+IMAKQ==";
      };
    };
    "mediasource-2.4.0" = {
      name = "mediasource";
      packageName = "mediasource";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mediasource/-/mediasource-2.4.0.tgz";
        sha512 = "SKUMrbFMHgiCUZFOWZcL0aiF/KgHx9SPIKzxrl6+7nMUMDK/ZnOmJdY/9wKzYeM0g3mybt3ueg+W+/mrYfmeFQ==";
      };
    };
    "memory-chunk-store-1.3.5" = {
      name = "memory-chunk-store";
      packageName = "memory-chunk-store";
      version = "1.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/memory-chunk-store/-/memory-chunk-store-1.3.5.tgz";
        sha512 = "E1Xc1U4ifk/FkC2ZsWhCaW1xg9HbE/OBmQTLe2Tr9c27YPSLbW7kw1cnb3kQWD1rDtErFJHa7mB9EVrs7aTx9g==";
      };
    };
    "mime-1.6.0" = {
      name = "mime";
      packageName = "mime";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-1.6.0.tgz";
        sha512 = "x0Vn8spI+wuJ1O6S7gnbaQg8Pxh4NNHb7KSINmEWKiPE4RKOplvijn+NkmYmmRgP68mc70j2EbeTFRsrswaQeg==";
      };
    };
    "mime-2.5.2" = {
      name = "mime";
      packageName = "mime";
      version = "2.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-2.5.2.tgz";
        sha512 = "tqkh47FzKeCPD2PUiPB6pkbMzsCasjxAfC62/Wap5qrUWcb+sFasXUC5I3gYM5iBM8v/Qpn4UK0x+j0iHyFPDg==";
      };
    };
    "mimic-response-1.0.1" = {
      name = "mimic-response";
      packageName = "mimic-response";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mimic-response/-/mimic-response-1.0.1.tgz";
        sha512 = "j5EctnkH7amfV/q5Hgmoal1g2QHFJRraOtmx0JpIqkxhBhI/lJSl1nMpQ45hVarwNETOoWEimndZ4QK0RHxuxQ==";
      };
    };
    "mimic-response-3.1.0" = {
      name = "mimic-response";
      packageName = "mimic-response";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mimic-response/-/mimic-response-3.1.0.tgz";
        sha512 = "z0yWI+4FDrrweS8Zmt4Ej5HdJmky15+L2e6Wgn3+iK5fWzb6T3fhNFq2+MeTRb064c6Wr4N/wv0DzQTjNzHNGQ==";
      };
    };
    "minimatch-3.0.4" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz";
        sha512 = "yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==";
      };
    };
    "minimist-1.2.5" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.5.tgz";
        sha512 = "FM9nNUYrRBAELZQT3xeZQ7fmMOBg6nWNmJKTcgsJeaLstP/UODVpGsr5OhXhhXg6f+qtJ8uiZ+PUxkDWcgIXLw==";
      };
    };
    "mkdirp-classic-0.5.3" = {
      name = "mkdirp-classic";
      packageName = "mkdirp-classic";
      version = "0.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp-classic/-/mkdirp-classic-0.5.3.tgz";
        sha512 = "gKLcREMhtuZRwRAfqP3RFW+TK4JqApVBtOIftVgjuABpAtpxhPGaDcfvbhNvD0B8iD1oUr/txX35NjcaY6Ns/A==";
      };
    };
    "moment-2.29.1" = {
      name = "moment";
      packageName = "moment";
      version = "2.29.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/moment/-/moment-2.29.1.tgz";
        sha512 = "kHmoybcPV8Sqy59DwNDY3Jefr64lK/by/da0ViFcuA4DH0vQg5Q6Ze5VimxkfQNSC+Mls/Kx53s7TjP1RhFEDQ==";
      };
    };
    "mp4-box-encoding-1.4.1" = {
      name = "mp4-box-encoding";
      packageName = "mp4-box-encoding";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mp4-box-encoding/-/mp4-box-encoding-1.4.1.tgz";
        sha512 = "2/PRtGGiqPc/VEhbm7xAQ+gbb7yzHjjMAv6MpAifr5pCpbh3fQUdj93uNgwPiTppAGu8HFKe3PeU+OdRyAxStA==";
      };
    };
    "mp4-stream-3.1.3" = {
      name = "mp4-stream";
      packageName = "mp4-stream";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/mp4-stream/-/mp4-stream-3.1.3.tgz";
        sha512 = "DUT8f0x2jHbZjNMdqe9h6lZdt6RENWTTdGn8z3TXa4uEsoltuNY9lCCij84mdm0q7xcV0E2W25WRxlKBMo4hSw==";
      };
    };
    "ms-2.0.0" = {
      name = "ms";
      packageName = "ms";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz";
        sha1 = "5608aeadfc00be6c2901df5f9861788de0d597c8";
      };
    };
    "ms-2.1.2" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.2.tgz";
        sha512 = "sGkPx+VjMtmA6MX27oA4FBFELFCZZ4S4XqeGOXCv68tT+jb3vk/RyaKWP0PTKyWtmLSM0b+adUTEvbs1PEaH2w==";
      };
    };
    "multistream-4.1.0" = {
      name = "multistream";
      packageName = "multistream";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/multistream/-/multistream-4.1.0.tgz";
        sha512 = "J1XDiAmmNpRCBfIWJv+n0ymC4ABcf/Pl+5YvC5B/D2f/2+8PtHvCNxMPKiQcZyi922Hq69J2YOpb1pTywfifyw==";
      };
    };
    "netmask-2.0.2" = {
      name = "netmask";
      packageName = "netmask";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/netmask/-/netmask-2.0.2.tgz";
        sha512 = "dBpDMdxv9Irdq66304OLfEmQ9tbNRFnFTuZiLo+bD+r332bBmMJ8GBLXklIXXgxd3+v9+KUnZaUR5PJMa75Gsg==";
      };
    };
    "network-address-1.1.2" = {
      name = "network-address";
      packageName = "network-address";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/network-address/-/network-address-1.1.2.tgz";
        sha1 = "4aa7bfd43f03f0b81c9702b13d6a858ddb326f3e";
      };
    };
    "next-event-1.0.0" = {
      name = "next-event";
      packageName = "next-event";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/next-event/-/next-event-1.0.0.tgz";
        sha1 = "e7778acde2e55802e0ad1879c39cf6f75eda61d8";
      };
    };
    "node-ssdp-2.9.1" = {
      name = "node-ssdp";
      packageName = "node-ssdp";
      version = "2.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-ssdp/-/node-ssdp-2.9.1.tgz";
        sha1 = "2d6ba8e7eff9bf5b338564f91f7ac5d5cdddc55b";
      };
    };
    "on-finished-2.3.0" = {
      name = "on-finished";
      packageName = "on-finished";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/on-finished/-/on-finished-2.3.0.tgz";
        sha1 = "20f1336481b083cd75337992a16971aa2d906947";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "open-8.2.1" = {
      name = "open";
      packageName = "open";
      version = "8.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/open/-/open-8.2.1.tgz";
        sha512 = "rXILpcQlkF/QuFez2BJDf3GsqpjGKbkUUToAIGo9A0Q6ZkoSGogZJulrUdwRkrAsoQvoZsrjCYt8+zblOk7JQQ==";
      };
    };
    "package-json-versionify-1.0.4" = {
      name = "package-json-versionify";
      packageName = "package-json-versionify";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/package-json-versionify/-/package-json-versionify-1.0.4.tgz";
        sha1 = "5860587a944873a6b7e6d26e8e51ffb22315bf17";
      };
    };
    "parse-torrent-9.1.3" = {
      name = "parse-torrent";
      packageName = "parse-torrent";
      version = "9.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-torrent/-/parse-torrent-9.1.3.tgz";
        sha512 = "/Yr951CvJM8S6TjMaqrsmMxeQEAjDeCX+MZ3hGXXc7DG2wqzp/rzOsHtDzIVqN6NsFRCqy6wYLF/W7Sgvq7bXw==";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "piece-length-2.0.1" = {
      name = "piece-length";
      packageName = "piece-length";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/piece-length/-/piece-length-2.0.1.tgz";
        sha512 = "dBILiDmm43y0JPISWEmVGKBETQjwJe6mSU9GND+P9KW0SJGUwoU/odyH1nbalOP9i8WSYuqf1lQnaj92Bhw+Ug==";
      };
    };
    "pify-2.3.0" = {
      name = "pify";
      packageName = "pify";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pify/-/pify-2.3.0.tgz";
        sha1 = "ed141a6ac043a849ea588498e7dca8b15330e90c";
      };
    };
    "prettier-bytes-1.0.4" = {
      name = "prettier-bytes";
      packageName = "prettier-bytes";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/prettier-bytes/-/prettier-bytes-1.0.4.tgz";
        sha1 = "994b02aa46f699c50b6257b5faaa7fe2557e62d6";
      };
    };
    "process-nextick-args-2.0.1" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-2.0.1.tgz";
        sha512 = "3ouUOpQhtgrbOa17J7+uxOTpITYWaGP7/AhoR3+A+/1e9skrzelGi/dXzEYyvbxubEF6Wn2ypscTKiKJFFn1ag==";
      };
    };
    "pump-3.0.0" = {
      name = "pump";
      packageName = "pump";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pump/-/pump-3.0.0.tgz";
        sha512 = "LwZy+p3SFs1Pytd/jYct4wpv49HiYCqd9Rlc5ZVdk0V+8Yzv6jR5Blk3TRmPL1ft69TxP0IMZGJ+WPFU2BFhww==";
      };
    };
    "queue-microtask-1.2.3" = {
      name = "queue-microtask";
      packageName = "queue-microtask";
      version = "1.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/queue-microtask/-/queue-microtask-1.2.3.tgz";
        sha512 = "NuaNSa6flKT5JaSYQzJok04JzTL1CA6aGhv5rfLW3PgqA+M2ChpZQnAC8h8i4ZFkBS8X5RqkDBHA7r4hej3K9A==";
      };
    };
    "random-access-file-2.2.0" = {
      name = "random-access-file";
      packageName = "random-access-file";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/random-access-file/-/random-access-file-2.2.0.tgz";
        sha512 = "B744003Mj7v3EcuPl9hCiB2Ot4aZjgtU2mV6yFY1THiWU/XfGf1uSadR+SlQdJcwHgAWeG7Lbos0aUqjtj8FQg==";
      };
    };
    "random-access-storage-1.4.1" = {
      name = "random-access-storage";
      packageName = "random-access-storage";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/random-access-storage/-/random-access-storage-1.4.1.tgz";
        sha512 = "DbCc2TIzOxPaHF6KCbr8zLtiYOJQQQCBHUVNHV/SckUQobCBB2YkDtbLdxGnPwPNpJfEyMWxDAm36A2xkbxxtw==";
      };
    };
    "random-iterate-1.0.1" = {
      name = "random-iterate";
      packageName = "random-iterate";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/random-iterate/-/random-iterate-1.0.1.tgz";
        sha1 = "f7d97d92dee6665ec5f6da08c7f963cad4b2ac99";
      };
    };
    "randombytes-2.1.0" = {
      name = "randombytes";
      packageName = "randombytes";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/randombytes/-/randombytes-2.1.0.tgz";
        sha512 = "vYl3iOX+4CKUWuxGi9Ukhie6fsqXqS9FE2Zaic4tNFD2N2QQaXOMFbuKK4QmDHC0JO6B1Zp41J0LpT0oR68amQ==";
      };
    };
    "range-parser-1.2.1" = {
      name = "range-parser";
      packageName = "range-parser";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/range-parser/-/range-parser-1.2.1.tgz";
        sha512 = "Hrgsx+orqoygnmhFbKaHE6c296J+HTAQXoxEF6gNupROmmGJRoyzfG3ccAveqCBrwr/2yxQ5BVd/GTl5agOwSg==";
      };
    };
    "range-slice-stream-2.0.0" = {
      name = "range-slice-stream";
      packageName = "range-slice-stream";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/range-slice-stream/-/range-slice-stream-2.0.0.tgz";
        sha512 = "PPYLwZ63lXi6Tv2EZ8w3M4FzC0rVqvxivaOVS8pXSp5FMIHFnvi4MWHL3UdFLhwSy50aNtJsgjY0mBC6oFL26Q==";
      };
    };
    "rc4-0.1.5" = {
      name = "rc4";
      packageName = "rc4";
      version = "0.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/rc4/-/rc4-0.1.5.tgz";
        sha1 = "08c6e04a0168f6eb621c22ab6cb1151bd9f4a64d";
      };
    };
    "readable-stream-2.3.7" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.3.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.3.7.tgz";
        sha512 = "Ebho8K4jIbHAxnuxi7o42OrZgF/ZTNcsZj6nRKyUmkhLFq8CHItp/fy6hQZuZmP/n3yZ9VBUbp4zz/mX8hmYPw==";
      };
    };
    "readable-stream-3.6.0" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "3.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-3.6.0.tgz";
        sha512 = "BViHy7LKeTz4oNnkcLJ+lVSL6vpiFeX6/d3oSH8zCW7UxP2onchk+vTGB143xuFjHS3deTgkKoXXymXqymiIdA==";
      };
    };
    "record-cache-1.1.1" = {
      name = "record-cache";
      packageName = "record-cache";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/record-cache/-/record-cache-1.1.1.tgz";
        sha512 = "L5hZlgWc7CmGbztnemQoKE1bLu9rtI2skOB0ttE4C5+TVszLE8Rd0YLTROSgvXKLAqPumS/soyN5tJW5wJLmJQ==";
      };
    };
    "render-media-4.1.0" = {
      name = "render-media";
      packageName = "render-media";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/render-media/-/render-media-4.1.0.tgz";
        sha512 = "F5BMWDmgATEoyPCtKjmGNTGN1ghoZlfRQ3MJh8dS/MrvIUIxupiof/Y9uahChipXcqQ57twVbgMmyQmuO1vokw==";
      };
    };
    "require-directory-2.1.1" = {
      name = "require-directory";
      packageName = "require-directory";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/require-directory/-/require-directory-2.1.1.tgz";
        sha1 = "8c64ad5fd30dab1c976e2344ffe7f792a6a6df42";
      };
    };
    "rimraf-3.0.2" = {
      name = "rimraf";
      packageName = "rimraf";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/rimraf/-/rimraf-3.0.2.tgz";
        sha512 = "JZkJMZkAGFFPP2YqXZXPbMlMBgsxzE8ILs4lMIX/2o0L9UBw9O/Y3o6wFw/i9YLapcUJWwqbi3kdxIPdC62TIA==";
      };
    };
    "run-parallel-1.2.0" = {
      name = "run-parallel";
      packageName = "run-parallel";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/run-parallel/-/run-parallel-1.2.0.tgz";
        sha512 = "5l4VyZR86LZ/lDxZTR6jqL8AFE2S0IFLMP26AbjsLVADxHdhB/c0GUsH+y39UfCi3dzz8OlQuPmnaJOMoDHQBA==";
      };
    };
    "run-parallel-limit-1.1.0" = {
      name = "run-parallel-limit";
      packageName = "run-parallel-limit";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/run-parallel-limit/-/run-parallel-limit-1.1.0.tgz";
        sha512 = "jJA7irRNM91jaKc3Hcl1npHsFLOXOoTkPCUL1JEa1R82O2miplXXRaGdjW/KM/98YQWDhJLiSs793CnXfblJUw==";
      };
    };
    "run-series-1.1.9" = {
      name = "run-series";
      packageName = "run-series";
      version = "1.1.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/run-series/-/run-series-1.1.9.tgz";
        sha512 = "Arc4hUN896vjkqCYrUXquBFtRZdv1PfLbTYP71efP6butxyQ0kWpiNJyAgsxscmQg1cqvHY32/UCBzXedTpU2g==";
      };
    };
    "rusha-0.8.14" = {
      name = "rusha";
      packageName = "rusha";
      version = "0.8.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/rusha/-/rusha-0.8.14.tgz";
        sha512 = "cLgakCUf6PedEu15t8kbsjnwIFFR2D4RfL+W3iWFJ4iac7z4B0ZI8fxy4R3J956kAI68HclCFGL8MPoUVC3qVA==";
      };
    };
    "safe-buffer-5.1.2" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.2.tgz";
        sha512 = "Gd2UZBJDkXlY7GbJxfsE8/nvKkUEU1G38c1siN6QP6a9PT9MmHB8GnpscSmMJSoF8LOIrt8ud/wPtojys4G6+g==";
      };
    };
    "safe-buffer-5.2.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.2.1.tgz";
        sha512 = "rp3So07KcdmmKbGvgaNxQSJr7bGVSVk5S9Eq1F+ppbRo70+YeaDxkw5Dd8NPN+GD6bjnYm2VuPuCXmpuYvmCXQ==";
      };
    };
    "sax-1.1.4" = {
      name = "sax";
      packageName = "sax";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/sax/-/sax-1.1.4.tgz";
        sha1 = "74b6d33c9ae1e001510f179a91168588f1aedaa9";
      };
    };
    "simple-concat-1.0.1" = {
      name = "simple-concat";
      packageName = "simple-concat";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/simple-concat/-/simple-concat-1.0.1.tgz";
        sha512 = "cSFtAPtRhljv69IK0hTVZQ+OfE9nePi/rtJmw5UjHeVyVroEqJXP1sFztKUy1qU+xvz3u/sfYJLa947b7nAN2Q==";
      };
    };
    "simple-get-2.8.1" = {
      name = "simple-get";
      packageName = "simple-get";
      version = "2.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/simple-get/-/simple-get-2.8.1.tgz";
        sha512 = "lSSHRSw3mQNUGPAYRqo7xy9dhKmxFXIjLjp4KHpf99GEH2VH7C3AM+Qfx6du6jhfUi6Vm7XnbEVEf7Wb6N8jRw==";
      };
    };
    "simple-get-4.0.0" = {
      name = "simple-get";
      packageName = "simple-get";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/simple-get/-/simple-get-4.0.0.tgz";
        sha512 = "ZalZGexYr3TA0SwySsr5HlgOOinS4Jsa8YB2GJ6lUNAazyAu4KG/VmzMTwAt2YVXzzVj8QmefmAonZIK2BSGcQ==";
      };
    };
    "simple-peer-9.11.0" = {
      name = "simple-peer";
      packageName = "simple-peer";
      version = "9.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/simple-peer/-/simple-peer-9.11.0.tgz";
        sha512 = "qvdNu/dGMHBm2uQ7oLhQBMhYlrOZC1ywXNCH/i8I4etxR1vrjCnU6ZSQBptndB1gcakjo2+w4OHo7Sjza1SHxg==";
      };
    };
    "simple-sha1-3.1.0" = {
      name = "simple-sha1";
      packageName = "simple-sha1";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/simple-sha1/-/simple-sha1-3.1.0.tgz";
        sha512 = "ArTptMRC1v08H8ihPD6l0wesKvMfF9e8XL5rIHPanI7kGOsSsbY514MwVu6X1PITHCTB2F08zB7cyEbfc4wQjg==";
      };
    };
    "simple-websocket-9.1.0" = {
      name = "simple-websocket";
      packageName = "simple-websocket";
      version = "9.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/simple-websocket/-/simple-websocket-9.1.0.tgz";
        sha512 = "8MJPnjRN6A8UCp1I+H/dSFyjwJhp6wta4hsVRhjf8w9qBHRzxYt14RaOcjvQnhD1N4yKOddEjflwMnQM4VtXjQ==";
      };
    };
    "speedometer-1.1.0" = {
      name = "speedometer";
      packageName = "speedometer";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/speedometer/-/speedometer-1.1.0.tgz";
        sha512 = "z/wAiTESw2XVPssY2XRcme4niTc4S5FkkJ4gknudtVoc33Zil8TdTxHy5torRcgqMqksJV2Yz8HQcvtbsnw0mQ==";
      };
    };
    "split-1.0.1" = {
      name = "split";
      packageName = "split";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/split/-/split-1.0.1.tgz";
        sha512 = "mTyOoPbrivtXnwnIxZRFYRrPNtEFKlpB2fvjSnCQUiAA6qAZzqwna5envK4uk6OIeP17CsdF3rSBGYVBsU0Tkg==";
      };
    };
    "stream-to-blob-2.0.1" = {
      name = "stream-to-blob";
      packageName = "stream-to-blob";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-to-blob/-/stream-to-blob-2.0.1.tgz";
        sha512 = "GXlqXt3svqwIVWoICenix5Poxi4KbCF0BdXXUbpU1X4vq1V8wmjiEIU3aFJzCGNFpKxfbnG0uoowS3nKUgSPYg==";
      };
    };
    "stream-to-blob-url-3.0.2" = {
      name = "stream-to-blob-url";
      packageName = "stream-to-blob-url";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-to-blob-url/-/stream-to-blob-url-3.0.2.tgz";
        sha512 = "PS6wT2ZyyR38Cy+lE6PBEI1ZmO2HdzZoLeDGG0zZbYikCZd0dh8FUoSeFzgWLItpBYw1WJmPVRLpykRV+lAWLQ==";
      };
    };
    "stream-with-known-length-to-buffer-1.0.4" = {
      name = "stream-with-known-length-to-buffer";
      packageName = "stream-with-known-length-to-buffer";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-with-known-length-to-buffer/-/stream-with-known-length-to-buffer-1.0.4.tgz";
        sha512 = "ztP79ug6S+I7td0Nd2GBeIKCm+vA54c+e60FY87metz5n/l6ydPELd2lxsljz8OpIhsRM9HkIiAwz85+S5G5/A==";
      };
    };
    "string-width-4.2.2" = {
      name = "string-width";
      packageName = "string-width";
      version = "4.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-4.2.2.tgz";
        sha512 = "XBJbT3N4JhVumXE0eoLU9DCjcaF92KLNqTmFCnG1pf8duUxFGwtP6AD6nkjw9a3IdiRtL3E2w3JDiE/xi3vOeA==";
      };
    };
    "string2compact-1.3.0" = {
      name = "string2compact";
      packageName = "string2compact";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/string2compact/-/string2compact-1.3.0.tgz";
        sha512 = "004ulKKANDuQilQsNxy2lisrpMG0qUJxBU+2YCEF7KziRyNR0Nredm2qk0f1V82nva59H3y9GWeHXE63HzGRFw==";
      };
    };
    "string_decoder-1.1.1" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.1.1.tgz";
        sha512 = "n/ShnvDi6FHbbVfviro+WojiFzv+s8MPMHBczVePfUpDJLwoLT0ht1l4YwBCbi8pJAveEEdnkHyPyTP/mzRfwg==";
      };
    };
    "string_decoder-1.3.0" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.3.0.tgz";
        sha512 = "hkRX8U1WjJFd8LsDJ2yQ/wWWxaopEsABU1XfkM8A+j0+85JAGppt16cr1Whg6KIbb4okU6Mql6BOj+uup/wKeA==";
      };
    };
    "strip-ansi-6.0.0" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-6.0.0.tgz";
        sha512 = "AuvKTrTfQNYNIctbR1K/YGTR1756GycPsg7b9bdV9Duqur4gv6aKqHXah67Z8ImS7WEz5QVcOtlfW2rZEugt6w==";
      };
    };
    "supports-color-7.2.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-7.2.0.tgz";
        sha512 = "qpCAvRl9stuOHveKsn7HncJRvv501qIacKzQlO/+Lwxc9+0q2wLyv4Dfvt80/DPn2pqOBsJdDiogXGR9+OvwRw==";
      };
    };
    "thirty-two-1.0.2" = {
      name = "thirty-two";
      packageName = "thirty-two";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/thirty-two/-/thirty-two-1.0.2.tgz";
        sha1 = "4ca2fffc02a51290d2744b9e3f557693ca6b627a";
      };
    };
    "through-2.3.8" = {
      name = "through";
      packageName = "through";
      version = "2.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/through/-/through-2.3.8.tgz";
        sha1 = "0dd4c9ffaabc357960b1b724115d7e0e86a2e1f5";
      };
    };
    "thunky-0.1.0" = {
      name = "thunky";
      packageName = "thunky";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/thunky/-/thunky-0.1.0.tgz";
        sha1 = "bf30146824e2b6e67b0f2d7a4ac8beb26908684e";
      };
    };
    "thunky-1.1.0" = {
      name = "thunky";
      packageName = "thunky";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/thunky/-/thunky-1.1.0.tgz";
        sha512 = "eHY7nBftgThBqOyHGVN+l8gF0BucP09fMo0oO/Lb0w1OF80dJv+lDVpXG60WMQvkcxAkNybKsrEIE3ZtKGmPrA==";
      };
    };
    "to-arraybuffer-1.0.1" = {
      name = "to-arraybuffer";
      packageName = "to-arraybuffer";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-arraybuffer/-/to-arraybuffer-1.0.1.tgz";
        sha1 = "7d229b1fcc637e466ca081180836a7aabff83f43";
      };
    };
    "torrent-discovery-9.4.0" = {
      name = "torrent-discovery";
      packageName = "torrent-discovery";
      version = "9.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/torrent-discovery/-/torrent-discovery-9.4.0.tgz";
        sha512 = "+YW9JGbO5bCuDw9YYW//p4iVLV0aP4C+AYrNQjL/+dSNPUtD1ufK1V8UZERt6rIoeNGhutkSVyeO4Fid9Tjxjg==";
      };
    };
    "torrent-piece-2.0.1" = {
      name = "torrent-piece";
      packageName = "torrent-piece";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/torrent-piece/-/torrent-piece-2.0.1.tgz";
        sha512 = "JLSOyvQVLI6JTWqioY4vFL0JkEUKQcaHQsU3loxkCvPTSttw8ePs2tFwsP4XIjw99Fz8EdOzt/4faykcbnPbCQ==";
      };
    };
    "typedarray-0.0.6" = {
      name = "typedarray";
      packageName = "typedarray";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/typedarray/-/typedarray-0.0.6.tgz";
        sha1 = "867ac74e3864187b1d3d47d996a78ec5c8830777";
      };
    };
    "typedarray-to-buffer-3.1.5" = {
      name = "typedarray-to-buffer";
      packageName = "typedarray-to-buffer";
      version = "3.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/typedarray-to-buffer/-/typedarray-to-buffer-3.1.5.tgz";
        sha512 = "zdu8XMNEDepKKR+XYOXAVPtWui0ly0NtohUscw+UmaHiAWT8hrV1rr//H6V+0DvJ3OQ19S979M0laLfX8rm82Q==";
      };
    };
    "uint64be-2.0.2" = {
      name = "uint64be";
      packageName = "uint64be";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/uint64be/-/uint64be-2.0.2.tgz";
        sha512 = "9QqdvpGQTXgxthP+lY4e/gIBy+RuqcBaC6JVwT5I3bDLgT/btL6twZMR0pI3/Fgah9G/pdwzIprE5gL6v9UvyQ==";
      };
    };
    "unordered-array-remove-1.0.2" = {
      name = "unordered-array-remove";
      packageName = "unordered-array-remove";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/unordered-array-remove/-/unordered-array-remove-1.0.2.tgz";
        sha1 = "c546e8f88e317a0cf2644c97ecb57dba66d250ef";
      };
    };
    "upnp-device-client-1.0.2" = {
      name = "upnp-device-client";
      packageName = "upnp-device-client";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/upnp-device-client/-/upnp-device-client-1.0.2.tgz";
        sha1 = "91f84705f2349bf89082855fff4e3006ac435337";
      };
    };
    "upnp-mediarenderer-client-1.4.0" = {
      name = "upnp-mediarenderer-client";
      packageName = "upnp-mediarenderer-client";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/upnp-mediarenderer-client/-/upnp-mediarenderer-client-1.4.0.tgz";
        sha512 = "F+C3Yceoz0j3ZWEchz5tpaOEqkbpObRUmeuPGc9+2u2YvC1CDbXGQ6mjbM10MDhnUJ0tTWYTufpj6xsWctnULw==";
      };
    };
    "url-join-4.0.1" = {
      name = "url-join";
      packageName = "url-join";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/url-join/-/url-join-4.0.1.tgz";
        sha512 = "jk1+QP6ZJqyOiuEI9AEWQfju/nB2Pw466kbA0LEZljHwKeMgd9WrAEgEGxjPDD2+TNbbb37rTyhEfrCXfuKXnA==";
      };
    };
    "ut_metadata-3.5.2" = {
      name = "ut_metadata";
      packageName = "ut_metadata";
      version = "3.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ut_metadata/-/ut_metadata-3.5.2.tgz";
        sha512 = "3XZZuJSeoIUyMYSuDbTbVtP4KAVGHPfU8nmHFkr8LJc+THCaUXwnu/2AV+LCSLarET/hL9IlbNfYTGrt6fOVuQ==";
      };
    };
    "ut_pex-3.0.1" = {
      name = "ut_pex";
      packageName = "ut_pex";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ut_pex/-/ut_pex-3.0.1.tgz";
        sha512 = "t1MHIDHSISgOJcmq8UM6Qv9/hRQYVaUvzqSNnXa5ATDbS9hXfhBpyBo2HcSyJtwPSHsmMtNui8G6yKirwJ8vow==";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "videostream-3.2.2" = {
      name = "videostream";
      packageName = "videostream";
      version = "3.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/videostream/-/videostream-3.2.2.tgz";
        sha512 = "4tz23yGGeATmbzj/ZnUm6wgQ4E1lzmMXu2mUA/c0G6adtWKxm1Di5YejdZdRsK6SdkLjKjhplFFYT7r+UUDKvA==";
      };
    };
    "vlc-command-1.2.0" = {
      name = "vlc-command";
      packageName = "vlc-command";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vlc-command/-/vlc-command-1.2.0.tgz";
        sha512 = "YTr1w5KmxRN5CBCvplKOD6g/OjwCl5iz+SIjDbq8gWTkByYZun5duHm+OLUkBlbJrCGvMyFyNhTMQxV4Ny0v8g==";
      };
    };
    "webtorrent-1.2.0" = {
      name = "webtorrent";
      packageName = "webtorrent";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/webtorrent/-/webtorrent-1.2.0.tgz";
        sha512 = "iSeWKHYYdgAQOpxjugzYOJ2gIF7JTJpNL3lEieOo3MvcNhLsVYEWJCfqaLb8hAHu/hfQGmQ6Hs2DCyGCE7PWiQ==";
      };
    };
    "webtorrent-cli-3.3.1" = {
      name = "webtorrent-cli";
      packageName = "webtorrent-cli";
      version = "3.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/webtorrent-cli/-/webtorrent-cli-3.3.1.tgz";
        sha512 = "C29onCkDUhQORBMG4+0JPOEC5zDnkXXB7ZJjJaC3WqmXvTWH4P7FfYys5uSXr/UzT3JjoqnwTWPjhunJZZkYxA==";
      };
    };
    "winreg-1.2.4" = {
      name = "winreg";
      packageName = "winreg";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/winreg/-/winreg-1.2.4.tgz";
        sha1 = "ba065629b7a925130e15779108cf540990e98d1b";
      };
    };
    "wrap-ansi-7.0.0" = {
      name = "wrap-ansi";
      packageName = "wrap-ansi";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrap-ansi/-/wrap-ansi-7.0.0.tgz";
        sha512 = "YVGIj2kamLSTxw6NsZjoBxfSwsn0ycdesmc4p+Q21c5zPuZ1pl+NfxVdxPtdHvmNVOQ6XSYG4AUtyt/Fi7D16Q==";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "ws-7.5.3" = {
      name = "ws";
      packageName = "ws";
      version = "7.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-7.5.3.tgz";
        sha512 = "kQ/dHIzuLrS6Je9+uv81ueZomEwH0qVYstcAQ4/Z93K8zeko9gtAbttJWzoC5ukqXY1PpoouV3+VSOqEAFt5wg==";
      };
    };
    "xml2js-0.4.23" = {
      name = "xml2js";
      packageName = "xml2js";
      version = "0.4.23";
      src = fetchurl {
        url = "https://registry.npmjs.org/xml2js/-/xml2js-0.4.23.tgz";
        sha512 = "ySPiMjM0+pLDftHgXY4By0uswI3SPKLDw/i3UXbnO8M/p28zqexCUoPmQFrYD+/1BzhGJSs2i1ERWKJAtiLrug==";
      };
    };
    "xmlbuilder-11.0.1" = {
      name = "xmlbuilder";
      packageName = "xmlbuilder";
      version = "11.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/xmlbuilder/-/xmlbuilder-11.0.1.tgz";
        sha512 = "fDlsI/kFEx7gLvbecc0/ohLG50fugQp8ryHzMTuW9vSa1GJ0XYWKnhsUx7oie3G98+r56aTQIUB4kht42R3JvA==";
      };
    };
    "y18n-5.0.8" = {
      name = "y18n";
      packageName = "y18n";
      version = "5.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/y18n/-/y18n-5.0.8.tgz";
        sha512 = "0pfFzegeDWJHJIAmTLRP2DwHjdF5s7jo9tuztdQxAhINCdvS+3nGINqPd00AphqJR/0LhANUS6/+7SCb98YOfA==";
      };
    };
    "yargs-17.0.1" = {
      name = "yargs";
      packageName = "yargs";
      version = "17.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/yargs/-/yargs-17.0.1.tgz";
        sha512 = "xBBulfCc8Y6gLFcrPvtqKz9hz8SO0l1Ni8GgDekvBX2ro0HRQImDGnikfc33cgzcYUSncapnNcZDjVFIH3f6KQ==";
      };
    };
    "yargs-parser-20.2.9" = {
      name = "yargs-parser";
      packageName = "yargs-parser";
      version = "20.2.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/yargs-parser/-/yargs-parser-20.2.9.tgz";
        sha512 = "y11nGElTIV+CT3Zv9t7VKl+Q3hTQoT9a1Qzezhhl6Rp21gJ/IVTW7Z3y9EWXhuUBC2Shnf+DX0antecpAwSP8w==";
      };
    };
  };
  args = {
    name = "webtorrent-cli";
    packageName = "webtorrent-cli";
    version = "3.3.1";
    src = ./.;
    dependencies = [
      sources."addr-to-ip-port-1.5.1"
      sources."ansi-regex-5.0.0"
      sources."ansi-styles-4.3.0"
      sources."balanced-match-1.0.2"
      sources."base64-js-1.5.1"
      sources."bencode-2.0.1"
      sources."bep53-range-1.1.0"
      sources."binary-search-1.3.6"
      sources."bitfield-4.0.0"
      (sources."bittorrent-dht-10.0.0" // {
        dependencies = [
          sources."debug-4.3.2"
          sources."ms-2.1.2"
        ];
      })
      (sources."bittorrent-lsd-1.1.0" // {
        dependencies = [
          sources."debug-4.3.2"
          sources."ms-2.1.2"
        ];
      })
      sources."bittorrent-peerid-1.3.3"
      (sources."bittorrent-protocol-3.4.2" // {
        dependencies = [
          sources."debug-4.3.2"
          sources."ms-2.1.2"
        ];
      })
      (sources."bittorrent-tracker-9.17.3" // {
        dependencies = [
          sources."debug-4.3.2"
          sources."decompress-response-6.0.0"
          sources."mimic-response-3.1.0"
          sources."ms-2.1.2"
          sources."simple-get-4.0.0"
        ];
      })
      sources."blob-to-buffer-1.2.9"
      sources."block-stream2-2.1.0"
      sources."bn.js-5.2.0"
      sources."brace-expansion-1.1.11"
      sources."browserify-package-json-1.0.1"
      sources."buffer-6.0.3"
      sources."buffer-alloc-1.2.0"
      sources."buffer-alloc-unsafe-1.1.0"
      sources."buffer-fill-1.0.0"
      sources."buffer-from-1.1.1"
      sources."cache-chunk-store-3.2.2"
      sources."chalk-4.1.1"
      sources."charset-1.0.1"
      sources."chrome-dgram-3.0.6"
      sources."chrome-dns-1.0.1"
      sources."chrome-net-3.3.4"
      sources."chunk-store-stream-4.3.0"
      sources."cliui-7.0.4"
      sources."color-convert-2.0.1"
      sources."color-name-1.1.4"
      sources."common-tags-1.8.0"
      sources."compact2string-1.4.1"
      sources."concat-map-0.0.1"
      (sources."concat-stream-1.6.2" // {
        dependencies = [
          sources."readable-stream-2.3.7"
          sources."safe-buffer-5.1.2"
          sources."string_decoder-1.1.1"
        ];
      })
      sources."core-util-is-1.0.2"
      sources."cpus-1.0.3"
      sources."create-torrent-4.7.0"
      sources."debug-2.6.9"
      sources."decompress-response-3.3.0"
      sources."define-lazy-prop-2.0.0"
      (sources."dlnacasts-0.1.0" // {
        dependencies = [
          sources."mime-1.6.0"
        ];
      })
      sources."ecstatic-4.1.4"
      sources."ee-first-1.1.1"
      sources."elementtree-0.1.7"
      sources."emoji-regex-8.0.0"
      sources."end-of-stream-1.4.4"
      sources."err-code-3.0.1"
      sources."escalade-3.1.1"
      sources."escape-html-1.0.3"
      sources."executable-4.1.1"
      sources."filestream-5.0.0"
      sources."freelist-1.0.3"
      (sources."fs-chunk-store-2.0.3" // {
        dependencies = [
          sources."thunky-1.1.0"
        ];
      })
      sources."fs.realpath-1.0.0"
      sources."get-browser-rtc-1.1.0"
      sources."get-caller-file-2.0.5"
      sources."get-stdin-8.0.0"
      sources."glob-7.1.7"
      sources."has-flag-4.0.0"
      sources."he-1.2.0"
      sources."http-node-git://github.com/feross/http-node#webtorrent"
      sources."http-parser-js-0.4.13"
      sources."ieee754-1.2.1"
      sources."immediate-chunk-store-2.2.0"
      sources."inflight-1.0.6"
      sources."inherits-2.0.4"
      sources."ip-1.1.5"
      sources."ip-set-2.1.0"
      sources."ipaddr.js-2.0.1"
      sources."is-ascii-1.0.0"
      sources."is-docker-2.2.1"
      sources."is-file-1.0.0"
      sources."is-fullwidth-code-point-3.0.0"
      sources."is-typedarray-1.0.0"
      sources."is-wsl-2.2.0"
      sources."isarray-1.0.0"
      sources."junk-3.1.0"
      sources."k-bucket-5.1.0"
      sources."k-rpc-5.1.0"
      sources."k-rpc-socket-1.11.1"
      sources."last-one-wins-1.0.4"
      (sources."load-ip-set-2.2.1" // {
        dependencies = [
          sources."decompress-response-6.0.0"
          sources."mimic-response-3.1.0"
          sources."simple-get-4.0.0"
        ];
      })
      sources."lru-3.1.0"
      (sources."lt_donthave-1.0.1" // {
        dependencies = [
          sources."debug-4.3.2"
          sources."ms-2.1.2"
        ];
      })
      sources."magnet-uri-6.2.0"
      sources."mediasource-2.4.0"
      sources."memory-chunk-store-1.3.5"
      sources."mime-2.5.2"
      sources."mimic-response-1.0.1"
      sources."minimatch-3.0.4"
      sources."minimist-1.2.5"
      sources."mkdirp-classic-0.5.3"
      sources."moment-2.29.1"
      sources."mp4-box-encoding-1.4.1"
      sources."mp4-stream-3.1.3"
      sources."ms-2.0.0"
      sources."multistream-4.1.0"
      sources."netmask-2.0.2"
      sources."network-address-1.1.2"
      sources."next-event-1.0.0"
      sources."node-ssdp-2.9.1"
      sources."on-finished-2.3.0"
      sources."once-1.4.0"
      sources."open-8.2.1"
      sources."package-json-versionify-1.0.4"
      (sources."parse-torrent-9.1.3" // {
        dependencies = [
          sources."decompress-response-6.0.0"
          sources."mimic-response-3.1.0"
          sources."simple-get-4.0.0"
        ];
      })
      sources."path-is-absolute-1.0.1"
      sources."piece-length-2.0.1"
      sources."pify-2.3.0"
      sources."prettier-bytes-1.0.4"
      sources."process-nextick-args-2.0.1"
      sources."pump-3.0.0"
      sources."queue-microtask-1.2.3"
      sources."random-access-file-2.2.0"
      sources."random-access-storage-1.4.1"
      sources."random-iterate-1.0.1"
      sources."randombytes-2.1.0"
      sources."range-parser-1.2.1"
      sources."range-slice-stream-2.0.0"
      sources."rc4-0.1.5"
      sources."readable-stream-3.6.0"
      sources."record-cache-1.1.1"
      (sources."render-media-4.1.0" // {
        dependencies = [
          sources."debug-4.3.2"
          sources."ms-2.1.2"
        ];
      })
      sources."require-directory-2.1.1"
      sources."rimraf-3.0.2"
      sources."run-parallel-1.2.0"
      sources."run-parallel-limit-1.1.0"
      sources."run-series-1.1.9"
      sources."rusha-0.8.14"
      sources."safe-buffer-5.2.1"
      sources."sax-1.1.4"
      sources."simple-concat-1.0.1"
      sources."simple-get-2.8.1"
      (sources."simple-peer-9.11.0" // {
        dependencies = [
          sources."debug-4.3.2"
          sources."ms-2.1.2"
        ];
      })
      sources."simple-sha1-3.1.0"
      (sources."simple-websocket-9.1.0" // {
        dependencies = [
          sources."debug-4.3.2"
          sources."ms-2.1.2"
        ];
      })
      sources."speedometer-1.1.0"
      sources."split-1.0.1"
      sources."stream-to-blob-2.0.1"
      sources."stream-to-blob-url-3.0.2"
      sources."stream-with-known-length-to-buffer-1.0.4"
      sources."string-width-4.2.2"
      (sources."string2compact-1.3.0" // {
        dependencies = [
          sources."ipaddr.js-1.9.1"
        ];
      })
      sources."string_decoder-1.3.0"
      sources."strip-ansi-6.0.0"
      sources."supports-color-7.2.0"
      sources."thirty-two-1.0.2"
      sources."through-2.3.8"
      sources."thunky-0.1.0"
      sources."to-arraybuffer-1.0.1"
      (sources."torrent-discovery-9.4.0" // {
        dependencies = [
          sources."debug-4.3.2"
          sources."ms-2.1.2"
        ];
      })
      sources."torrent-piece-2.0.1"
      sources."typedarray-0.0.6"
      sources."typedarray-to-buffer-3.1.5"
      sources."uint64be-2.0.2"
      sources."unordered-array-remove-1.0.2"
      sources."upnp-device-client-1.0.2"
      sources."upnp-mediarenderer-client-1.4.0"
      sources."url-join-4.0.1"
      (sources."ut_metadata-3.5.2" // {
        dependencies = [
          sources."debug-4.3.2"
          sources."ms-2.1.2"
        ];
      })
      sources."ut_pex-3.0.1"
      sources."util-deprecate-1.0.2"
      sources."videostream-3.2.2"
      sources."vlc-command-1.2.0"
      (sources."webtorrent-1.2.0" // {
        dependencies = [
          sources."debug-4.3.2"
          sources."decompress-response-6.0.0"
          sources."mimic-response-3.1.0"
          sources."ms-2.1.2"
          sources."simple-get-4.0.0"
        ];
      })
      sources."webtorrent-cli-3.3.1"
      sources."winreg-1.2.4"
      sources."wrap-ansi-7.0.0"
      sources."wrappy-1.0.2"
      sources."ws-7.5.3"
      sources."xml2js-0.4.23"
      sources."xmlbuilder-11.0.1"
      sources."y18n-5.0.8"
      sources."yargs-17.0.1"
      sources."yargs-parser-20.2.9"
    ];
    buildInputs = globalBuildInputs;
    meta = {
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
