# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@webtorrent/http-node-1.3.0" = {
      name = "_at_webtorrent_slash_http-node";
      packageName = "@webtorrent/http-node";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@webtorrent/http-node/-/http-node-1.3.0.tgz";
        sha512 = "GWZQKroPES4z91Ijx6zsOsb7+USOxjy66s8AoTWg0HiBBdfnbtf9aeh3Uav0MgYn4BL8Q7tVSUpd0gGpngKGEQ==";
      };
    };
    "addr-to-ip-port-1.5.4" = {
      name = "addr-to-ip-port";
      packageName = "addr-to-ip-port";
      version = "1.5.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/addr-to-ip-port/-/addr-to-ip-port-1.5.4.tgz";
        sha512 = "ByxmJgv8vjmDcl3IDToxL2yrWFrRtFpZAToY0f46XFXl8zS081t7El5MXIodwm7RC6DhHBRoOSMLFSPKCtHukg==";
      };
    };
    "ansi-escapes-4.3.2" = {
      name = "ansi-escapes";
      packageName = "ansi-escapes";
      version = "4.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-escapes/-/ansi-escapes-4.3.2.tgz";
        sha512 = "gKXj5ALrKWQLsYG9jlTRmR/xKluxHV+Z9QEwNIgCfM1/uwPMCuzVVnh5mwTd+OuBZcwSIMbqssNWRm1lE51QaQ==";
      };
    };
    "ansi-regex-5.0.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-5.0.1.tgz";
        sha512 = "quJQXlTSUGL2LH9SUXo8VwsY4soanhgo6LNSm84E1LBcE8s3O0wpdiRzyR9z/ZZJMlMWv37qOOb9pdJlMUEKFQ==";
      };
    };
    "ansi-styles-4.3.0" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-4.3.0.tgz";
        sha512 = "zbB9rCJAT1rbjiVDb2hqKFHNYLxgtk8NURxZ3IZwD3F6NtxbXZQCnnSi1Lkx+IDohdPlFp222wVALIheZJQSEg==";
      };
    };
    "b4a-1.5.3" = {
      name = "b4a";
      packageName = "b4a";
      version = "1.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/b4a/-/b4a-1.5.3.tgz";
        sha512 = "1aCQIzQJK7G0z1Una75tWMlwVAR8o+QHoAlnWc5XAxRVBESY9WsitfBgM5nPyDBP5HrhPU1Np4Pq2Y7CJQ+tVw==";
      };
    };
    "balanced-match-1.0.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.2.tgz";
        sha512 = "3oSeUO0TMV67hN1AmbXsK4yaqU7tjiHlbxRDZOpH0KW9+CeX4bRAaX0Anxt0tx2MrpRpWwQaPwIlISEJhYU5Pw==";
      };
    };
    "base64-js-1.5.1" = {
      name = "base64-js";
      packageName = "base64-js";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64-js/-/base64-js-1.5.1.tgz";
        sha512 = "AKpaYlHn8t4SVbOHCy+b5+KKgvR4vrsD8vbvrbiQJps7fKDTkjkDry6ji0rUJjC0kzbNePLwzxq8iypo41qeWA==";
      };
    };
    "bencode-2.0.3" = {
      name = "bencode";
      packageName = "bencode";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/bencode/-/bencode-2.0.3.tgz";
        sha512 = "D/vrAD4dLVX23NalHwb8dSvsUsxeRPO8Y7ToKA015JQYq69MLDOMkC0uGZYA/MPpltLO8rt8eqFC2j8DxjTZ/w==";
      };
    };
    "bep53-range-1.1.1" = {
      name = "bep53-range";
      packageName = "bep53-range";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bep53-range/-/bep53-range-1.1.1.tgz";
        sha512 = "ct6s33iiwRCUPp9KXnJ4QMWDgHIgaw36caK/5XEQ9L8dCzSQlJt1Vk6VmHh1VD4AlGCAI4C2zmtfItifBBPrhQ==";
      };
    };
    "binary-search-1.3.6" = {
      name = "binary-search";
      packageName = "binary-search";
      version = "1.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/binary-search/-/binary-search-1.3.6.tgz";
        sha512 = "nbE1WxOTTrUWIfsfZ4aHGYu5DOuNkbxGokjV6Z2kxfJK3uaAb8zNK1muzOeipoLHZjInT4Br88BHpzevc681xA==";
      };
    };
    "bitfield-4.1.0" = {
      name = "bitfield";
      packageName = "bitfield";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bitfield/-/bitfield-4.1.0.tgz";
        sha512 = "6cEDG3K+PK9f+B7WyhWYjp09bqSa+uaAaecVA7Y5giFixyVe1s6HKGnvOqYNR4Mi4fBMjfDPLBpHkKvzzgP7kg==";
      };
    };
    "bittorrent-dht-10.0.4" = {
      name = "bittorrent-dht";
      packageName = "bittorrent-dht";
      version = "10.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/bittorrent-dht/-/bittorrent-dht-10.0.4.tgz";
        sha512 = "Yx5cZXU4R+mUbxR2PbKdvOVTizOrePPF8NT3WGCXX5qzJVt8gF8gq9GMBWcmNjHUBYHVigDaRf030hxQ2dJWUg==";
      };
    };
    "bittorrent-lsd-1.1.1" = {
      name = "bittorrent-lsd";
      packageName = "bittorrent-lsd";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bittorrent-lsd/-/bittorrent-lsd-1.1.1.tgz";
        sha512 = "dWxU2Mr2lU6jzIKgZrTsXgeXDCIcYpR1b6f2n89fn7juwPAYbNU04OgWjcQPLiNliY0filsX5CQAWntVErpk+Q==";
      };
    };
    "bittorrent-peerid-1.3.4" = {
      name = "bittorrent-peerid";
      packageName = "bittorrent-peerid";
      version = "1.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/bittorrent-peerid/-/bittorrent-peerid-1.3.4.tgz";
        sha512 = "Xzk1FJFHmsc9H8IKFtDUkfAZIT1HW8r6UqajfZBBxWmpA1v7FsPO8xPFtnFzCqcXlPN3yi8dDmlqZCemyB7P8w==";
      };
    };
    "bittorrent-protocol-3.5.5" = {
      name = "bittorrent-protocol";
      packageName = "bittorrent-protocol";
      version = "3.5.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/bittorrent-protocol/-/bittorrent-protocol-3.5.5.tgz";
        sha512 = "cfzO//WtJGNLHXS58a4exJCSq1U0dkP2DZCQxgADInYFPdOfV1EmtpEN9toLOluVCXJRYAdwW5H6Li/hrn697A==";
      };
    };
    "bittorrent-tracker-9.19.0" = {
      name = "bittorrent-tracker";
      packageName = "bittorrent-tracker";
      version = "9.19.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bittorrent-tracker/-/bittorrent-tracker-9.19.0.tgz";
        sha512 = "09d0aD2b+MC+zWvWajkUAKkYMynYW4tMbTKiRSthKtJZbafzEoNQSUHyND24SoCe3ZOb2fKfa6fu2INAESL9wA==";
      };
    };
    "bl-4.1.0" = {
      name = "bl";
      packageName = "bl";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bl/-/bl-4.1.0.tgz";
        sha512 = "1W07cM9gS6DcLperZfFSj+bWLtaPGSOHWhPiGzXmvVJbRLdG82sH/Kn8EtW1VqWVA54AKf2h5k5BbnIbwF3h6w==";
      };
    };
    "blob-to-buffer-1.2.9" = {
      name = "blob-to-buffer";
      packageName = "blob-to-buffer";
      version = "1.2.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/blob-to-buffer/-/blob-to-buffer-1.2.9.tgz";
        sha512 = "BF033y5fN6OCofD3vgHmNtwZWRcq9NLyyxyILx9hfMy1sXYy4ojFl765hJ2lP0YaN2fuxPaLO2Vzzoxy0FLFFA==";
      };
    };
    "block-stream2-2.1.0" = {
      name = "block-stream2";
      packageName = "block-stream2";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/block-stream2/-/block-stream2-2.1.0.tgz";
        sha512 = "suhjmLI57Ewpmq00qaygS8UgEq2ly2PCItenIyhMqVjo4t4pGzqMvfgJuX8iWTeSDdfSSqS6j38fL4ToNL7Pfg==";
      };
    };
    "bn.js-5.2.1" = {
      name = "bn.js";
      packageName = "bn.js";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bn.js/-/bn.js-5.2.1.tgz";
        sha512 = "eXRvHzWyYPBuB4NBy0cmYQjGitUrtqwbvlzP3G6VFnNRbsZQIxQ10PbKKHt8gZ/HW/D/747aDl+QkDqg3KQLMQ==";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "browserify-package-json-1.0.1" = {
      name = "browserify-package-json";
      packageName = "browserify-package-json";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-package-json/-/browserify-package-json-1.0.1.tgz";
        sha512 = "CikZxJGNyNOBERbeALo0NUUeJgHs5NyEvuYChX/PcsBV91TAvEq4hYDaWSenSieT8XwAutNnS3FGvyzIMOughQ==";
      };
    };
    "buffer-5.7.1" = {
      name = "buffer";
      packageName = "buffer";
      version = "5.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer/-/buffer-5.7.1.tgz";
        sha512 = "EHcyIPBQ4BSGlvjB16k5KgAJ27CIsHY/2JBmCRReo48y9rQ3MaUzWX3KVlBa4U7MyX02HdVj0K7C3WaB3ju7FQ==";
      };
    };
    "buffer-6.0.3" = {
      name = "buffer";
      packageName = "buffer";
      version = "6.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer/-/buffer-6.0.3.tgz";
        sha512 = "FTiCpNxtwiZZHEZbcbTIcZjERVICn9yq/pDFkTl95/AxzD1naBctN7YO68riM/gLSDY7sdrMby8hofADYuuqOA==";
      };
    };
    "buffer-alloc-1.2.0" = {
      name = "buffer-alloc";
      packageName = "buffer-alloc";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-alloc/-/buffer-alloc-1.2.0.tgz";
        sha512 = "CFsHQgjtW1UChdXgbyJGtnm+O/uLQeZdtbDo8mfUgYXCHSM1wgrVxXm6bSyrUuErEb+4sYVGCzASBRot7zyrow==";
      };
    };
    "buffer-alloc-unsafe-1.1.0" = {
      name = "buffer-alloc-unsafe";
      packageName = "buffer-alloc-unsafe";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-alloc-unsafe/-/buffer-alloc-unsafe-1.1.0.tgz";
        sha512 = "TEM2iMIEQdJ2yjPJoSIsldnleVaAk1oW3DBVUykyOLsEsFmEc9kn+SFFPz+gl54KQNxlDnAwCXosOS9Okx2xAg==";
      };
    };
    "buffer-fill-1.0.0" = {
      name = "buffer-fill";
      packageName = "buffer-fill";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-fill/-/buffer-fill-1.0.0.tgz";
        sha512 = "T7zexNBwiiaCOGDg9xNX9PBmjrubblRkENuptryuI64URkXDFum9il/JGL8Lm8wYfAXpredVXXZz7eMHilimiQ==";
      };
    };
    "buffer-from-1.1.2" = {
      name = "buffer-from";
      packageName = "buffer-from";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-from/-/buffer-from-1.1.2.tgz";
        sha512 = "E+XQCRwSbaaiChtv6k6Dwgc+bx+Bs6vuKJHHl5kox/BaKbhiXzqQOwK4cO22yElGp2OCmjwVhT3HmxgyPGnJfQ==";
      };
    };
    "cache-chunk-store-3.2.2" = {
      name = "cache-chunk-store";
      packageName = "cache-chunk-store";
      version = "3.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/cache-chunk-store/-/cache-chunk-store-3.2.2.tgz";
        sha512 = "2lJdWbgHFFxcSth9s2wpId3CR3v1YC63KjP4T9WhpW7LWlY7Hiiei3QwwqzkWqlJTfR8lSy9F5kRQECeyj+yQA==";
      };
    };
    "chalk-4.1.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-4.1.2.tgz";
        sha512 = "oKnbhFyRIXpUuez8iBMmyEa4nbj4IOQyuhc/wy9kY7/WVPcwIO9VA668Pu8RkO7+0G76SLROeyw9CpQ061i4mA==";
      };
    };
    "chardet-0.7.0" = {
      name = "chardet";
      packageName = "chardet";
      version = "0.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/chardet/-/chardet-0.7.0.tgz";
        sha512 = "mT8iDcrh03qDGRRmoA2hmBJnxpllMR+0/0qlzjqZES6NdiWDcZkCNAk4rPFZ9Q85r27unkiNNg8ZOiwZXBHwcA==";
      };
    };
    "charset-1.0.1" = {
      name = "charset";
      packageName = "charset";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/charset/-/charset-1.0.1.tgz";
        sha512 = "6dVyOOYjpfFcL1Y4qChrAoQLRHvj2ziyhcm0QJlhOcAhykL/k1kTUPbeo+87MNRTRdk2OIIsIXbuF3x2wi5EXg==";
      };
    };
    "chrome-dgram-3.0.6" = {
      name = "chrome-dgram";
      packageName = "chrome-dgram";
      version = "3.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/chrome-dgram/-/chrome-dgram-3.0.6.tgz";
        sha512 = "bqBsUuaOiXiqxXt/zA/jukNJJ4oaOtc7ciwqJpZVEaaXwwxqgI2/ZdG02vXYWUhHGziDlvGMQWk0qObgJwVYKA==";
      };
    };
    "chrome-dns-1.0.1" = {
      name = "chrome-dns";
      packageName = "chrome-dns";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/chrome-dns/-/chrome-dns-1.0.1.tgz";
        sha512 = "HqsYJgIc8ljJJOqOzLphjAs79EUuWSX3nzZi2LNkzlw3GIzAeZbaSektC8iT/tKvLqZq8yl1GJu5o6doA4TRbg==";
      };
    };
    "chrome-net-3.3.4" = {
      name = "chrome-net";
      packageName = "chrome-net";
      version = "3.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/chrome-net/-/chrome-net-3.3.4.tgz";
        sha512 = "Jzy2EnzmE+ligqIZUsmWnck9RBXLuUy6CaKyuNMtowFG3ZvLt8d+WBJCTPEludV0DHpIKjAOlwjFmTaEdfdWCw==";
      };
    };
    "chunk-store-stream-4.3.0" = {
      name = "chunk-store-stream";
      packageName = "chunk-store-stream";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/chunk-store-stream/-/chunk-store-stream-4.3.0.tgz";
        sha512 = "qby+/RXoiMoTVtPiylWZt7KFF1jy6M829TzMi2hxZtBIH9ptV19wxcft6zGiXLokJgCbuZPGNGab6DWHqiSEKw==";
      };
    };
    "cli-cursor-3.1.0" = {
      name = "cli-cursor";
      packageName = "cli-cursor";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli-cursor/-/cli-cursor-3.1.0.tgz";
        sha512 = "I/zHAwsKf9FqGoXM4WWRACob9+SNukZTd94DWF57E4toouRulbCxcUh6RKUEOQlYTHJnzkPMySvPNaaSLNfLZw==";
      };
    };
    "cli-spinners-2.6.1" = {
      name = "cli-spinners";
      packageName = "cli-spinners";
      version = "2.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli-spinners/-/cli-spinners-2.6.1.tgz";
        sha512 = "x/5fWmGMnbKQAaNwN+UZlV79qBLM9JFnJuJ03gIi5whrob0xV0ofNVHy9DhwGdsMJQc2OKv0oGmLzvaqvAVv+g==";
      };
    };
    "cli-width-3.0.0" = {
      name = "cli-width";
      packageName = "cli-width";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli-width/-/cli-width-3.0.0.tgz";
        sha512 = "FxqpkPPwu1HjuN93Omfm4h8uIanXofW0RxVEW3k5RKx+mJJYSthzNhp32Kzxxy3YAEZ/Dc/EWN1vZRY0+kOhbw==";
      };
    };
    "cliui-7.0.4" = {
      name = "cliui";
      packageName = "cliui";
      version = "7.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/cliui/-/cliui-7.0.4.tgz";
        sha512 = "OcRE68cOsVMXp1Yvonl/fzkQOyjLSu/8bhPDfQt0e0/Eb283TKP20Fs2MqoPsr9SwA595rRCA+QMzYc9nBP+JQ==";
      };
    };
    "clone-1.0.4" = {
      name = "clone";
      packageName = "clone";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/clone/-/clone-1.0.4.tgz";
        sha512 = "JQHZ2QMW6l3aH/j6xCqQThY/9OH4D/9ls34cgkUBiEeocRTU04tHfKPBsUK1PqZCUQM7GiA0IIXJSuXHI64Kbg==";
      };
    };
    "clone-2.1.2" = {
      name = "clone";
      packageName = "clone";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/clone/-/clone-2.1.2.tgz";
        sha512 = "3Pe/CF1Nn94hyhIYpjtiLhdCoEoz0DqQ+988E9gmeEdQZlojxnOb74wctFyuwWQHzqyf9X7C7MG8juUpqBJT8w==";
      };
    };
    "color-convert-2.0.1" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-2.0.1.tgz";
        sha512 = "RRECPsj7iu/xb5oKYcsFHSppFNnsj/52OVTRKb4zP5onXwVF3zVmmToNcOfGC+CRDpfK/U584fMg38ZHCaElKQ==";
      };
    };
    "color-name-1.1.4" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.4.tgz";
        sha512 = "dOy+3AuW3a2wNbZHIuMZpTcgjGuLU/uBL/ubcZF9OXbDo8ff4O8yVp5Bf0efS8uEoYo5q4Fx7dY9OgQGXgAsQA==";
      };
    };
    "common-tags-1.8.2" = {
      name = "common-tags";
      packageName = "common-tags";
      version = "1.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/common-tags/-/common-tags-1.8.2.tgz";
        sha512 = "gk/Z852D2Wtb//0I+kRFNKKE9dIIVirjoqPoA1wJU+XePVXZfGeBpk45+A1rKO4Q43prqWBNY/MiIeRLbPWUaA==";
      };
    };
    "compact2string-1.4.1" = {
      name = "compact2string";
      packageName = "compact2string";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/compact2string/-/compact2string-1.4.1.tgz";
        sha512 = "3D+EY5nsRhqnOwDxveBv5T8wGo4DEvYxjDtPGmdOX+gfr5gE92c2RC0w2wa+xEefm07QuVqqcF3nZJUZ92l/og==";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha512 = "/Srv4dswyQNBfohGpz9o6Yb3Gz3SrUDqBH5rTuhGR7ahtlbYKnVxw2bCFMRljaA7EXHaXZ8wsHdodFvbkhKmqg==";
      };
    };
    "concat-stream-1.6.2" = {
      name = "concat-stream";
      packageName = "concat-stream";
      version = "1.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-stream/-/concat-stream-1.6.2.tgz";
        sha512 = "27HBghJxjiZtIk3Ycvn/4kbJk/1uZuJFfuPEns6LaEvpvG1f0hTea8lilrouyo9mVc2GWdcEZ8OLoGmSADlrCw==";
      };
    };
    "core-util-is-1.0.3" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.3.tgz";
        sha512 = "ZQBvi1DcpJ4GDqanjucZ2Hj3wEO5pZDS89BWbkcrvdxksJorwUDDZamX9ldFkp9aw2lmBDLgkObEA4DWNJ9FYQ==";
      };
    };
    "cpus-1.0.3" = {
      name = "cpus";
      packageName = "cpus";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/cpus/-/cpus-1.0.3.tgz";
        sha512 = "PXHBvGLuL69u55IkLa5e5838fLhIMHxmkV4ge42a8alGyn7BtawYgI0hQ849EedvtHIOLNNH3i6eQU1BiE9SUA==";
      };
    };
    "create-torrent-5.0.2" = {
      name = "create-torrent";
      packageName = "create-torrent";
      version = "5.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/create-torrent/-/create-torrent-5.0.2.tgz";
        sha512 = "tNelixVeEkjiyeAuCW7uWFl1ARA+YapyZvdSWw6U3AXe/VXpxR4ihFNfjOzmvc5TBqK5EkGdsoKXAEKfQ8xlmQ==";
      };
    };
    "debug-2.6.9" = {
      name = "debug";
      packageName = "debug";
      version = "2.6.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.6.9.tgz";
        sha512 = "bC7ElrdJaJnPbAP+1EotYvqZsb3ecl5wi6Bfi6BJTUcNowp6cvspg0jXznRTKDjm/E7AdgFBVeAPVMNcKGsHMA==";
      };
    };
    "debug-4.3.4" = {
      name = "debug";
      packageName = "debug";
      version = "4.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.3.4.tgz";
        sha512 = "PRWFHuSU3eDtQJPvnNY7Jcket1j0t5OuOsFzPPzsekD52Zl8qUfFIPEiswXqIvHWGVHOgX+7G/vCNNhehwxfkQ==";
      };
    };
    "decompress-response-3.3.0" = {
      name = "decompress-response";
      packageName = "decompress-response";
      version = "3.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/decompress-response/-/decompress-response-3.3.0.tgz";
        sha512 = "BzRPQuY1ip+qDonAOz42gRm/pg9F768C+npV/4JOsxRC2sq+Rlk+Q4ZCAsOhnIaMrgarILY+RMUIvMmmX1qAEA==";
      };
    };
    "decompress-response-6.0.0" = {
      name = "decompress-response";
      packageName = "decompress-response";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/decompress-response/-/decompress-response-6.0.0.tgz";
        sha512 = "aW35yZM6Bb/4oJlZncMH2LCoZtJXTRxES17vE3hoRiowU2kWHaJKFkSBDnDR+cm9J+9QhXmREyIfv0pji9ejCQ==";
      };
    };
    "defaults-1.0.3" = {
      name = "defaults";
      packageName = "defaults";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/defaults/-/defaults-1.0.3.tgz";
        sha512 = "s82itHOnYrN0Ib8r+z7laQz3sdE+4FP3d9Q7VLO7U+KRT+CR0GsWuyHxzdAY82I7cXv0G/twrqomTJLOssO5HA==";
      };
    };
    "define-lazy-prop-2.0.0" = {
      name = "define-lazy-prop";
      packageName = "define-lazy-prop";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/define-lazy-prop/-/define-lazy-prop-2.0.0.tgz";
        sha512 = "Ds09qNh8yw3khSjiJjiUInaGX9xlqZDY7JVryGxdxV7NPeuqQfplOpQ66yJFZut3jLa5zOwkXw1g9EI2uKh4Og==";
      };
    };
    "dlnacasts-0.1.0" = {
      name = "dlnacasts";
      packageName = "dlnacasts";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dlnacasts/-/dlnacasts-0.1.0.tgz";
        sha512 = "JsNDoe2UbFzsXRdOHmGK8JO1SR/3Dj7J9LCmTgo35ppYQ0dR2O+oe8T2kABBF4+Qas4auaILQ4rul+LWMhtEdw==";
      };
    };
    "ecstatic-4.1.4" = {
      name = "ecstatic";
      packageName = "ecstatic";
      version = "4.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/ecstatic/-/ecstatic-4.1.4.tgz";
        sha512 = "8E4ZLK4uRuB9pwywGpy/B9vcz4gCp6IY7u4cMbeCINr/fjb1v+0wf0Ae2XlfSnG8xZYnE4uaJBjFkYI0bqcIdw==";
      };
    };
    "ee-first-1.1.1" = {
      name = "ee-first";
      packageName = "ee-first";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ee-first/-/ee-first-1.1.1.tgz";
        sha512 = "WMwm9LhRUo+WUaRN+vRuETqG89IgZphVSNkdFgeb6sS/E4OrDIN7t48CAewSHXc6C8lefD8KKfr5vY61brQlow==";
      };
    };
    "elementtree-0.1.7" = {
      name = "elementtree";
      packageName = "elementtree";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/elementtree/-/elementtree-0.1.7.tgz";
        sha512 = "wkgGT6kugeQk/P6VZ/f4T+4HB41BVgNBq5CDIZVbQ02nvTVqAiVTbskxxu3eA/X96lMlfYOwnLQpN2v5E1zDEg==";
      };
    };
    "emoji-regex-8.0.0" = {
      name = "emoji-regex";
      packageName = "emoji-regex";
      version = "8.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/emoji-regex/-/emoji-regex-8.0.0.tgz";
        sha512 = "MSjYzcWNOA0ewAHpz0MxpYFvwg6yjy1NG3xteoqz644VCo/RPgnr1/GGt+ic3iJTzQ8Eu3TdM14SawnVUmGE6A==";
      };
    };
    "end-of-stream-1.4.4" = {
      name = "end-of-stream";
      packageName = "end-of-stream";
      version = "1.4.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/end-of-stream/-/end-of-stream-1.4.4.tgz";
        sha512 = "+uw1inIHVPQoaVuHzRyXd21icM+cnt4CzD5rW+NC1wjOUSTOs+Te7FOv7AhN7vS9x/oIyhLP5PR1H+phQAHu5Q==";
      };
    };
    "err-code-3.0.1" = {
      name = "err-code";
      packageName = "err-code";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/err-code/-/err-code-3.0.1.tgz";
        sha512 = "GiaH0KJUewYok+eeY05IIgjtAe4Yltygk9Wqp1V5yVWLdhf0hYZchRjNIT9bb0mSwRcIusT3cx7PJUf3zEIfUA==";
      };
    };
    "escalade-3.1.1" = {
      name = "escalade";
      packageName = "escalade";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/escalade/-/escalade-3.1.1.tgz";
        sha512 = "k0er2gUkLf8O0zKJiAhmkTnJlTvINGv7ygDNPbeIsX/TJjGJZHuh9B2UxbsaEkmlEo9MfhrSzmhIlhRlI2GXnw==";
      };
    };
    "escape-html-1.0.3" = {
      name = "escape-html";
      packageName = "escape-html";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-html/-/escape-html-1.0.3.tgz";
        sha512 = "NiSupZ4OeuGwr68lGIeym/ksIZMJodUGOSCZ/FSnTxcrekbvqrgdUxlJOMpijaKZVjAJrWrGs/6Jy8OMuyj9ow==";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha512 = "vbRorB5FUQWvla16U8R/qgaFIya2qGzwDrNmCZuYKrbdSUMG6I1ZCGQRefkRVhuOkIGVne7BQ35DSfo1qvJqFg==";
      };
    };
    "events-3.3.0" = {
      name = "events";
      packageName = "events";
      version = "3.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/events/-/events-3.3.0.tgz";
        sha512 = "mQw+2fkQbALzQ7V0MY0IqdnXNOeTtP4r0lN9z7AAawCXgqea7bDii20AYrIBrFd/Hx0M2Ocz6S111CaFkUcb0Q==";
      };
    };
    "external-editor-3.1.0" = {
      name = "external-editor";
      packageName = "external-editor";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/external-editor/-/external-editor-3.1.0.tgz";
        sha512 = "hMQ4CX1p1izmuLYyZqLMO/qGNw10wSv9QDCPfzXfyFrOaCSSoRfqE1Kf1s5an66J5JZC62NewG+mK49jOCtQew==";
      };
    };
    "fast-fifo-1.1.0" = {
      name = "fast-fifo";
      packageName = "fast-fifo";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-fifo/-/fast-fifo-1.1.0.tgz";
        sha512 = "Kl29QoNbNvn4nhDsLYjyIAaIqaJB6rBx5p3sL9VjaefJ+eMFBWVZiaoguaoZfzEKr5RhAti0UgM8703akGPJ6g==";
      };
    };
    "figures-3.2.0" = {
      name = "figures";
      packageName = "figures";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/figures/-/figures-3.2.0.tgz";
        sha512 = "yaduQFRKLXYOGgEn6AZau90j3ggSOyiqXU0F9JZfeXYhNa+Jk4X+s45A2zg5jns87GAFa34BBm2kXw4XpNcbdg==";
      };
    };
    "filestream-5.0.0" = {
      name = "filestream";
      packageName = "filestream";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/filestream/-/filestream-5.0.0.tgz";
        sha512 = "5H3RqSaJp12THfZiNWodYM7TiKfQvrpX+EIOrB1XvCceTys4yvfEIl8wDp+/yI8qj6Bxym8m0NYWwVXDAet/+A==";
      };
    };
    "freelist-1.0.3" = {
      name = "freelist";
      packageName = "freelist";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/freelist/-/freelist-1.0.3.tgz";
        sha512 = "Ji7fEnMdZDGbS5oXElpRJsn9jPvBR8h/037D3bzreNmS8809cISq/2D9//JbA/TaZmkkN8cmecXwmQHmM+NHhg==";
      };
    };
    "fs-chunk-store-2.0.5" = {
      name = "fs-chunk-store";
      packageName = "fs-chunk-store";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs-chunk-store/-/fs-chunk-store-2.0.5.tgz";
        sha512 = "z3c2BmyaHdQTtIVXJDQOvwZVWN2gNU//0IYKK2LuPr+cZyGoIrgDwI4iDASaTUyQbOBtyg/k6GuDZepB6jQIPw==";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha512 = "OO0pH2lK6a0hZnAdau5ItzHPI6pUlvI7jMVnxUQRtw4owF2wk8lOSabtGDCTP4Ggrg2MbGnWO9X8K1t4+fGMDw==";
      };
    };
    "get-browser-rtc-1.1.0" = {
      name = "get-browser-rtc";
      packageName = "get-browser-rtc";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-browser-rtc/-/get-browser-rtc-1.1.0.tgz";
        sha512 = "MghbMJ61EJrRsDe7w1Bvqt3ZsBuqhce5nrn/XAwgwOXhcsz53/ltdxOse1h/8eKXj5slzxdsz56g5rzOFSGwfQ==";
      };
    };
    "get-caller-file-2.0.5" = {
      name = "get-caller-file";
      packageName = "get-caller-file";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-caller-file/-/get-caller-file-2.0.5.tgz";
        sha512 = "DyFP3BM/3YHTQOCUL/w0OZHR0lpKeGrxotcHWcqNEdnltqFwXVfhEBQ94eIo34AfQpo0rGki4cyIiftY06h2Fg==";
      };
    };
    "get-stdin-8.0.0" = {
      name = "get-stdin";
      packageName = "get-stdin";
      version = "8.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-stdin/-/get-stdin-8.0.0.tgz";
        sha512 = "sY22aA6xchAzprjyqmSEQv4UbAAzRN0L2dQB0NlN5acTTK9Don6nhoc3eAbUnpZiCANAMfd/+40kVdKfFygohg==";
      };
    };
    "glob-7.2.3" = {
      name = "glob";
      packageName = "glob";
      version = "7.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.2.3.tgz";
        sha512 = "nFR0zLpU2YCaRxwoCJvL6UvCH2JFyFVIvwTLsIf21AuHlMskA1hhTdk+LlYJtOlYt9v6dvszD2BGRqBL+iQK9Q==";
      };
    };
    "has-flag-4.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-4.0.0.tgz";
        sha512 = "EykJT/Q1KjTWctppgIAgfSO0tKVuZUjhgMr17kqTumMl6Afv3EISleU7qZUzoXDFTAHTDC4NOoG/ZxU3EvlMPQ==";
      };
    };
    "he-1.2.0" = {
      name = "he";
      packageName = "he";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/he/-/he-1.2.0.tgz";
        sha512 = "F/1DnUGPopORZi0ni+CvrCgHQ5FyEAHRLSApuYWMmrbSwoN2Mn/7k+Gl38gJnR7yyDZk6WLXwiGod1JOWNDKGw==";
      };
    };
    "http-parser-js-0.4.13" = {
      name = "http-parser-js";
      packageName = "http-parser-js";
      version = "0.4.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-parser-js/-/http-parser-js-0.4.13.tgz";
        sha512 = "u8u5ZaG0Tr/VvHlucK2ufMuOp4/5bvwgneXle+y228K5rMbJOlVjThONcaAw3ikAy8b2OO9RfEucdMHFz3UWMA==";
      };
    };
    "iconv-lite-0.4.24" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.4.24";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.4.24.tgz";
        sha512 = "v3MXnZAcvnywkTUEZomIActle7RXXeedOR31wwl7VlyoXO4Qi9arvSenNQWne1TcRwhCL1HwLI21bEqdpj8/rA==";
      };
    };
    "ieee754-1.2.1" = {
      name = "ieee754";
      packageName = "ieee754";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ieee754/-/ieee754-1.2.1.tgz";
        sha512 = "dcyqhDvX1C46lXZcVqCpK+FtMRQVdIMN6/Df5js2zouUsqG7I6sFxitIC+7KYK29KdXOLHdu9zL4sFnoVQnqaA==";
      };
    };
    "immediate-chunk-store-2.2.0" = {
      name = "immediate-chunk-store";
      packageName = "immediate-chunk-store";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/immediate-chunk-store/-/immediate-chunk-store-2.2.0.tgz";
        sha512 = "1bHBna0hCa6arRXicu91IiL9RvvkbNYLVq+mzWdaLGZC3hXvX4doh8e1dLhMKez5siu63CYgO5NrGJbRX5lbPA==";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha512 = "k92I/b08q4wvFscXCLvqfsHCrjrF7yiXsQuIVvVE7N82W3+aqpzuUdBbfhWcy/FZR3/4IgflMgKLOsvPDrGCJA==";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "inquirer-8.2.4" = {
      name = "inquirer";
      packageName = "inquirer";
      version = "8.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inquirer/-/inquirer-8.2.4.tgz";
        sha512 = "nn4F01dxU8VeKfq192IjLsxu0/OmMZ4Lg3xKAns148rCaXP6ntAoEkVYZThWjwON8AlzdZZi6oqnhNbxUG9hVg==";
      };
    };
    "ip-1.1.8" = {
      name = "ip";
      packageName = "ip";
      version = "1.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/ip/-/ip-1.1.8.tgz";
        sha512 = "PuExPYUiu6qMBQb4l06ecm6T6ujzhmh+MeJcW9wa89PoAz5pvd4zPgN5WJV104mb6S2T1AwNIAaB70JNrLQWhg==";
      };
    };
    "ip-set-2.1.0" = {
      name = "ip-set";
      packageName = "ip-set";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ip-set/-/ip-set-2.1.0.tgz";
        sha512 = "JdHz4tSMx1IeFj8yEcQU0i58qiSkOlmZXkZ8+HJ0ROV5KcgLRDO9F703oJ1GeZCvqggrcCbmagD/V7hghY62wA==";
      };
    };
    "ipaddr.js-2.0.1" = {
      name = "ipaddr.js";
      packageName = "ipaddr.js";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ipaddr.js/-/ipaddr.js-2.0.1.tgz";
        sha512 = "1qTgH9NG+IIJ4yfKs2e6Pp1bZg8wbDbKHT21HrLIeYBTRLgMYKnMTPAuI3Lcs61nfx5h1xlXnbJtH1kX5/d/ng==";
      };
    };
    "is-ascii-1.0.0" = {
      name = "is-ascii";
      packageName = "is-ascii";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-ascii/-/is-ascii-1.0.0.tgz";
        sha512 = "CXMaB/+EWCSGlLPs7ZlXRBpaPRRSRnrOfq0N3+RGeCZfqQaHQtiDLlkPCn63+LCkRUc1iRE0AXiI+sm2/Hi3qQ==";
      };
    };
    "is-docker-2.2.1" = {
      name = "is-docker";
      packageName = "is-docker";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-docker/-/is-docker-2.2.1.tgz";
        sha512 = "F+i2BKsFrH66iaUFc0woD8sLy8getkwTwtOBjvs56Cx4CgJDeKQeqfz8wAYiSb8JOprWhHH5p77PbmYCvvUuXQ==";
      };
    };
    "is-file-1.0.0" = {
      name = "is-file";
      packageName = "is-file";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-file/-/is-file-1.0.0.tgz";
        sha512 = "ZGMuc+xA8mRnrXtmtf2l/EkIW2zaD2LSBWlaOVEF6yH4RTndHob65V4SwWWdtGKVthQfXPVKsXqw4TDUjbVxVQ==";
      };
    };
    "is-fullwidth-code-point-3.0.0" = {
      name = "is-fullwidth-code-point";
      packageName = "is-fullwidth-code-point";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-3.0.0.tgz";
        sha512 = "zymm5+u+sCsSWyD9qNaejV3DFvhCKclKdizYaJUuHA83RLjb7nSuGnddCHGv0hk+KY7BMAlsWeK4Ueg6EV6XQg==";
      };
    };
    "is-interactive-1.0.0" = {
      name = "is-interactive";
      packageName = "is-interactive";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-interactive/-/is-interactive-1.0.0.tgz";
        sha512 = "2HvIEKRoqS62guEC+qBjpvRubdX910WCMuJTZ+I9yvqKU2/12eSL549HMwtabb4oupdj2sMP50k+XJfB/8JE6w==";
      };
    };
    "is-typedarray-1.0.0" = {
      name = "is-typedarray";
      packageName = "is-typedarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-typedarray/-/is-typedarray-1.0.0.tgz";
        sha512 = "cyA56iCMHAh5CdzjJIa4aohJyeO1YbwLi3Jc35MmRU6poroFjIGZzUzupGiRPOjgHg9TLu43xbpwXk523fMxKA==";
      };
    };
    "is-unicode-supported-0.1.0" = {
      name = "is-unicode-supported";
      packageName = "is-unicode-supported";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-unicode-supported/-/is-unicode-supported-0.1.0.tgz";
        sha512 = "knxG2q4UC3u8stRGyAVJCOdxFmv5DZiRcdlIaAQXAbSfJya+OhopNotLQrstBhququ4ZpuKbDc/8S6mgXgPFPw==";
      };
    };
    "is-wsl-2.2.0" = {
      name = "is-wsl";
      packageName = "is-wsl";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-wsl/-/is-wsl-2.2.0.tgz";
        sha512 = "fKzAra0rGJUUBwGBgNkHZuToZcn+TtXHpeCgmkMJMMYx1sQDYaCSyjJBSCa2nH1DGm7s3n1oBnohoVTBaN7Lww==";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha512 = "VLghIWNM6ELQzo7zwmcg0NmTVyWKYjvIeM83yjp0wRDTmUnrM678fQbcKBo6n2CJEF0szoG//ytg+TKla89ALQ==";
      };
    };
    "junk-3.1.0" = {
      name = "junk";
      packageName = "junk";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/junk/-/junk-3.1.0.tgz";
        sha512 = "pBxcB3LFc8QVgdggvZWyeys+hnrNWg4OcZIU/1X59k5jQdLBlCsYGRQaz234SqoRLTCgMH00fY0xRJH+F9METQ==";
      };
    };
    "k-bucket-5.1.0" = {
      name = "k-bucket";
      packageName = "k-bucket";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/k-bucket/-/k-bucket-5.1.0.tgz";
        sha512 = "Fac7iINEovXIWU20GPnOMLUbjctiS+cnmyjC4zAUgvs3XPf1vo9akfCHkigftSic/jiKqKl+KA3a/vFcJbHyCg==";
      };
    };
    "k-rpc-5.1.0" = {
      name = "k-rpc";
      packageName = "k-rpc";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/k-rpc/-/k-rpc-5.1.0.tgz";
        sha512 = "FGc+n70Hcjoa/X2JTwP+jMIOpBz+pkRffHnSl9yrYiwUxg3FIgD50+u1ePfJUOnRCnx6pbjmVk5aAeB1wIijuQ==";
      };
    };
    "k-rpc-socket-1.11.1" = {
      name = "k-rpc-socket";
      packageName = "k-rpc-socket";
      version = "1.11.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/k-rpc-socket/-/k-rpc-socket-1.11.1.tgz";
        sha512 = "8xtA8oqbZ6v1Niryp2/g4GxW16EQh5MvrUylQoOG+zcrDff5CKttON2XUXvMwlIHq4/2zfPVFiinAccJ+WhxoA==";
      };
    };
    "last-one-wins-1.0.4" = {
      name = "last-one-wins";
      packageName = "last-one-wins";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/last-one-wins/-/last-one-wins-1.0.4.tgz";
        sha512 = "t+KLJFkHPQk8lfN6WBOiGkiUXoub+gnb2XTYI2P3aiISL+94xgZ1vgz1SXN/N4hthuOoLXarXfBZPUruyjQtfA==";
      };
    };
    "limiter-1.1.5" = {
      name = "limiter";
      packageName = "limiter";
      version = "1.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/limiter/-/limiter-1.1.5.tgz";
        sha512 = "FWWMIEOxz3GwUI4Ts/IvgVy6LPvoMPgjMdQ185nN6psJyBJ4yOpzqm695/h5umdLJg2vW3GR5iG11MAkR2AzJA==";
      };
    };
    "load-ip-set-2.2.1" = {
      name = "load-ip-set";
      packageName = "load-ip-set";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/load-ip-set/-/load-ip-set-2.2.1.tgz";
        sha512 = "G3hQXehU2LTOp52e+lPffpK4EvidfjwbvHaGqmFcp4ptiZagR4xFdL+D08kMX906dxeqZyWhfonEjdUxrWcldg==";
      };
    };
    "lodash-4.17.21" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz";
        sha512 = "v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==";
      };
    };
    "log-symbols-4.1.0" = {
      name = "log-symbols";
      packageName = "log-symbols";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/log-symbols/-/log-symbols-4.1.0.tgz";
        sha512 = "8XPvpAA8uyhfteu8pIvQxpJZ7SYYdpUivZpGy6sFsBuKRY/7rQGavedeB8aK+Zkyq6upMFVL/9AW6vOYzfRyLg==";
      };
    };
    "lru-3.1.0" = {
      name = "lru";
      packageName = "lru";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru/-/lru-3.1.0.tgz";
        sha512 = "5OUtoiVIGU4VXBOshidmtOsvBIvcQR6FD/RzWSvaeHyxCGB+PCUCu+52lqMfdc0h/2CLvHhZS4TwUmMQrrMbBQ==";
      };
    };
    "lt_donthave-1.0.1" = {
      name = "lt_donthave";
      packageName = "lt_donthave";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lt_donthave/-/lt_donthave-1.0.1.tgz";
        sha512 = "PfOXfDN9GnUjlNHjjxKQuMxPC8s12iSrnmg+Ff1BU1uLn7S1BFAKzpZCu6Gwg3WsCUvTZrZoDSHvy6B/j+N4/Q==";
      };
    };
    "magnet-uri-6.2.0" = {
      name = "magnet-uri";
      packageName = "magnet-uri";
      version = "6.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/magnet-uri/-/magnet-uri-6.2.0.tgz";
        sha512 = "O9AgdDwT771fnUj0giPYu/rACpz8173y8UXCSOdLITjOVfBenZ9H9q3FqQmveK+ORUMuD+BkKNSZP8C3+IMAKQ==";
      };
    };
    "mediasource-2.4.0" = {
      name = "mediasource";
      packageName = "mediasource";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mediasource/-/mediasource-2.4.0.tgz";
        sha512 = "SKUMrbFMHgiCUZFOWZcL0aiF/KgHx9SPIKzxrl6+7nMUMDK/ZnOmJdY/9wKzYeM0g3mybt3ueg+W+/mrYfmeFQ==";
      };
    };
    "memory-chunk-store-1.3.5" = {
      name = "memory-chunk-store";
      packageName = "memory-chunk-store";
      version = "1.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/memory-chunk-store/-/memory-chunk-store-1.3.5.tgz";
        sha512 = "E1Xc1U4ifk/FkC2ZsWhCaW1xg9HbE/OBmQTLe2Tr9c27YPSLbW7kw1cnb3kQWD1rDtErFJHa7mB9EVrs7aTx9g==";
      };
    };
    "mime-1.6.0" = {
      name = "mime";
      packageName = "mime";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-1.6.0.tgz";
        sha512 = "x0Vn8spI+wuJ1O6S7gnbaQg8Pxh4NNHb7KSINmEWKiPE4RKOplvijn+NkmYmmRgP68mc70j2EbeTFRsrswaQeg==";
      };
    };
    "mime-2.6.0" = {
      name = "mime";
      packageName = "mime";
      version = "2.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-2.6.0.tgz";
        sha512 = "USPkMeET31rOMiarsBNIHZKLGgvKc/LrjofAnBlOttf5ajRvqiRA8QsenbcooctK6d6Ts6aqZXBA+XbkKthiQg==";
      };
    };
    "mime-3.0.0" = {
      name = "mime";
      packageName = "mime";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-3.0.0.tgz";
        sha512 = "jSCU7/VB1loIWBZe14aEYHU/+1UMEHoaO7qxCOVJOw9GgH72VAWppxNcjU+x9a2k3GSIBXNKxXQFqRvvZ7vr3A==";
      };
    };
    "mimic-fn-2.1.0" = {
      name = "mimic-fn";
      packageName = "mimic-fn";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mimic-fn/-/mimic-fn-2.1.0.tgz";
        sha512 = "OqbOk5oEQeAZ8WXWydlu9HJjz9WVdEIvamMCcXmuqUYjTknH/sqsWvhQ3vgwKFRR1HpjvNBKQ37nbJgYzGqGcg==";
      };
    };
    "mimic-response-1.0.1" = {
      name = "mimic-response";
      packageName = "mimic-response";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mimic-response/-/mimic-response-1.0.1.tgz";
        sha512 = "j5EctnkH7amfV/q5Hgmoal1g2QHFJRraOtmx0JpIqkxhBhI/lJSl1nMpQ45hVarwNETOoWEimndZ4QK0RHxuxQ==";
      };
    };
    "mimic-response-3.1.0" = {
      name = "mimic-response";
      packageName = "mimic-response";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mimic-response/-/mimic-response-3.1.0.tgz";
        sha512 = "z0yWI+4FDrrweS8Zmt4Ej5HdJmky15+L2e6Wgn3+iK5fWzb6T3fhNFq2+MeTRb064c6Wr4N/wv0DzQTjNzHNGQ==";
      };
    };
    "minimatch-3.1.2" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.1.2.tgz";
        sha512 = "J7p63hRiAjw1NDEww1W7i37+ByIrOWO5XQQAzZ3VOcL0PNybwpfmV/N05zFAzwQ9USyEcX6t3UO+K5aqBQOIHw==";
      };
    };
    "minimist-1.2.6" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.6.tgz";
        sha512 = "Jsjnk4bw3YJqYzbdyBiNsPWHPfO++UGG749Cxs6peCu5Xg4nrena6OVxOYxrQTqww0Jmwt+Ref8rggumkTLz9Q==";
      };
    };
    "mkdirp-classic-0.5.3" = {
      name = "mkdirp-classic";
      packageName = "mkdirp-classic";
      version = "0.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp-classic/-/mkdirp-classic-0.5.3.tgz";
        sha512 = "gKLcREMhtuZRwRAfqP3RFW+TK4JqApVBtOIftVgjuABpAtpxhPGaDcfvbhNvD0B8iD1oUr/txX35NjcaY6Ns/A==";
      };
    };
    "moment-2.29.3" = {
      name = "moment";
      packageName = "moment";
      version = "2.29.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/moment/-/moment-2.29.3.tgz";
        sha512 = "c6YRvhEo//6T2Jz/vVtYzqBzwvPT95JBQ+smCytzf7c50oMZRsR/a4w88aD34I+/QVSfnoAnSBFPJHItlOMJVw==";
      };
    };
    "mp4-box-encoding-1.4.1" = {
      name = "mp4-box-encoding";
      packageName = "mp4-box-encoding";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mp4-box-encoding/-/mp4-box-encoding-1.4.1.tgz";
        sha512 = "2/PRtGGiqPc/VEhbm7xAQ+gbb7yzHjjMAv6MpAifr5pCpbh3fQUdj93uNgwPiTppAGu8HFKe3PeU+OdRyAxStA==";
      };
    };
    "mp4-stream-3.1.3" = {
      name = "mp4-stream";
      packageName = "mp4-stream";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/mp4-stream/-/mp4-stream-3.1.3.tgz";
        sha512 = "DUT8f0x2jHbZjNMdqe9h6lZdt6RENWTTdGn8z3TXa4uEsoltuNY9lCCij84mdm0q7xcV0E2W25WRxlKBMo4hSw==";
      };
    };
    "ms-2.0.0" = {
      name = "ms";
      packageName = "ms";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz";
        sha512 = "Tpp60P6IUJDTuOq/5Z8cdskzJujfwqfOTkrwIwj7IRISpnkJnT6SyJ4PCPnGMoFjC9ddhal5KVIYtAt97ix05A==";
      };
    };
    "ms-2.1.2" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.2.tgz";
        sha512 = "sGkPx+VjMtmA6MX27oA4FBFELFCZZ4S4XqeGOXCv68tT+jb3vk/RyaKWP0PTKyWtmLSM0b+adUTEvbs1PEaH2w==";
      };
    };
    "multistream-4.1.0" = {
      name = "multistream";
      packageName = "multistream";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/multistream/-/multistream-4.1.0.tgz";
        sha512 = "J1XDiAmmNpRCBfIWJv+n0ymC4ABcf/Pl+5YvC5B/D2f/2+8PtHvCNxMPKiQcZyi922Hq69J2YOpb1pTywfifyw==";
      };
    };
    "mute-stream-0.0.8" = {
      name = "mute-stream";
      packageName = "mute-stream";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/mute-stream/-/mute-stream-0.0.8.tgz";
        sha512 = "nnbWWOkoWyUsTjKrhgD0dcz22mdkSnpYqbEjIm2nhwhuxlSkpywJmBo8h0ZqJdkp73mb90SssHkN4rsRaBAfAA==";
      };
    };
    "netmask-2.0.2" = {
      name = "netmask";
      packageName = "netmask";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/netmask/-/netmask-2.0.2.tgz";
        sha512 = "dBpDMdxv9Irdq66304OLfEmQ9tbNRFnFTuZiLo+bD+r332bBmMJ8GBLXklIXXgxd3+v9+KUnZaUR5PJMa75Gsg==";
      };
    };
    "network-address-1.1.2" = {
      name = "network-address";
      packageName = "network-address";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/network-address/-/network-address-1.1.2.tgz";
        sha512 = "Q6878fmvItA1mE7H9Il46lONgFgTzX2f98zkS0c2YlkCACzNjwvum/8Kq693IQpxe9zy+w+Zm/4p0wQreLEtZw==";
      };
    };
    "next-event-1.0.0" = {
      name = "next-event";
      packageName = "next-event";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/next-event/-/next-event-1.0.0.tgz";
        sha512 = "IXGPhl/yAiUU597gz+k5OYxYZkmLSWTcPPcpQjWABud9OK6m/ZNLrVdcEu4e7NgmOObFIhgZVg1jecPYT/6AoA==";
      };
    };
    "node-ssdp-2.9.1" = {
      name = "node-ssdp";
      packageName = "node-ssdp";
      version = "2.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-ssdp/-/node-ssdp-2.9.1.tgz";
        sha512 = "yGUSsm7HKxcv1XU0X6BIMWaOl/SaXqrIhwZCdklmAzwjG6qt+hnJwzs+VigCuRMP+jhSyoVBvHnoc95VgxbcuQ==";
      };
    };
    "on-finished-2.4.1" = {
      name = "on-finished";
      packageName = "on-finished";
      version = "2.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/on-finished/-/on-finished-2.4.1.tgz";
        sha512 = "oVlzkg3ENAhCk2zdv7IJwd/QUD4z2RxRwpkcGY8psCVcCYZNq4wYnVWALHM+brtuJjePWiYF/ClmuDr8Ch5+kg==";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha512 = "lNaJgI+2Q5URQBkccEKHTQOPaXdUxnZZElQTZY0MFUAuaEqe1E+Nyvgdz/aIyNi6Z9MzO5dv1H8n58/GELp3+w==";
      };
    };
    "onetime-5.1.2" = {
      name = "onetime";
      packageName = "onetime";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/onetime/-/onetime-5.1.2.tgz";
        sha512 = "kbpaSSGJTWdAY5KPVeMOKXSrPtr8C8C7wodJbcsd51jRnmD+GZu8Y0VoU6Dm5Z4vWr0Ig/1NKuWRKf7j5aaYSg==";
      };
    };
    "open-8.4.0" = {
      name = "open";
      packageName = "open";
      version = "8.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/open/-/open-8.4.0.tgz";
        sha512 = "XgFPPM+B28FtCCgSb9I+s9szOC1vZRSwgWsRUA5ylIxRTgKozqjOCrVOqGsYABPYK5qnfqClxZTFBa8PKt2v6Q==";
      };
    };
    "ora-5.4.1" = {
      name = "ora";
      packageName = "ora";
      version = "5.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ora/-/ora-5.4.1.tgz";
        sha512 = "5b6Y85tPxZZ7QytO+BQzysW31HJku27cRIlkbAXaNx+BdcVi+LlRFmVXzeF6a7JCwJpyw5c4b+YSVImQIrBpuQ==";
      };
    };
    "os-tmpdir-1.0.2" = {
      name = "os-tmpdir";
      packageName = "os-tmpdir";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-tmpdir/-/os-tmpdir-1.0.2.tgz";
        sha512 = "D2FR03Vir7FIu45XBY20mTb+/ZSWB00sjU9jdQXt83gDrI4Ztz5Fs7/yy74g2N5SVQY4xY1qDr4rNddwYRVX0g==";
      };
    };
    "package-json-versionify-1.0.4" = {
      name = "package-json-versionify";
      packageName = "package-json-versionify";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/package-json-versionify/-/package-json-versionify-1.0.4.tgz";
        sha512 = "mtKKtCeSZMtWcc5hHJS6OlEGP7J9g7WN6vWCCZi2hCXFag/Zmjokh6WFFTQb9TuMnBcZpRjhhMQyOyglPCAahw==";
      };
    };
    "parse-torrent-9.1.5" = {
      name = "parse-torrent";
      packageName = "parse-torrent";
      version = "9.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-torrent/-/parse-torrent-9.1.5.tgz";
        sha512 = "K8FXRwTOaZMI0/xuv0dpng1MVHZRtMJ0jRWBJ3qZWVNTrC1MzWUxm9QwaXDz/2qPhV2XC4UIHI92IGHwseAwaA==";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha512 = "AVbw3UJ2e9bq64vSaS9Am0fje1Pa8pbGqTTsmXfaIiMpnr5DlDhfJOuLj9Sf95ZPVDAUerDfEk88MPmPe7UCQg==";
      };
    };
    "piece-length-2.0.1" = {
      name = "piece-length";
      packageName = "piece-length";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/piece-length/-/piece-length-2.0.1.tgz";
        sha512 = "dBILiDmm43y0JPISWEmVGKBETQjwJe6mSU9GND+P9KW0SJGUwoU/odyH1nbalOP9i8WSYuqf1lQnaj92Bhw+Ug==";
      };
    };
    "prettier-bytes-1.0.4" = {
      name = "prettier-bytes";
      packageName = "prettier-bytes";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/prettier-bytes/-/prettier-bytes-1.0.4.tgz";
        sha512 = "dLbWOa4xBn+qeWeIF60qRoB6Pk2jX5P3DIVgOQyMyvBpu931Q+8dXz8X0snJiFkQdohDDLnZQECjzsAj75hgZQ==";
      };
    };
    "process-nextick-args-2.0.1" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-2.0.1.tgz";
        sha512 = "3ouUOpQhtgrbOa17J7+uxOTpITYWaGP7/AhoR3+A+/1e9skrzelGi/dXzEYyvbxubEF6Wn2ypscTKiKJFFn1ag==";
      };
    };
    "pump-3.0.0" = {
      name = "pump";
      packageName = "pump";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pump/-/pump-3.0.0.tgz";
        sha512 = "LwZy+p3SFs1Pytd/jYct4wpv49HiYCqd9Rlc5ZVdk0V+8Yzv6jR5Blk3TRmPL1ft69TxP0IMZGJ+WPFU2BFhww==";
      };
    };
    "queue-microtask-1.2.3" = {
      name = "queue-microtask";
      packageName = "queue-microtask";
      version = "1.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/queue-microtask/-/queue-microtask-1.2.3.tgz";
        sha512 = "NuaNSa6flKT5JaSYQzJok04JzTL1CA6aGhv5rfLW3PgqA+M2ChpZQnAC8h8i4ZFkBS8X5RqkDBHA7r4hej3K9A==";
      };
    };
    "queue-tick-1.0.0" = {
      name = "queue-tick";
      packageName = "queue-tick";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/queue-tick/-/queue-tick-1.0.0.tgz";
        sha512 = "ULWhjjE8BmiICGn3G8+1L9wFpERNxkf8ysxkAer4+TFdRefDaXOCV5m92aMB9FtBVmn/8sETXLXY6BfW7hyaWQ==";
      };
    };
    "random-access-file-2.2.1" = {
      name = "random-access-file";
      packageName = "random-access-file";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/random-access-file/-/random-access-file-2.2.1.tgz";
        sha512 = "RGU0xmDqdOyEiynob1KYSeh8+9c9Td1MJ74GT1viMEYAn8SJ9oBtWCXLsYZukCF46yududHOdM449uRYbzBrZQ==";
      };
    };
    "random-access-storage-1.4.3" = {
      name = "random-access-storage";
      packageName = "random-access-storage";
      version = "1.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/random-access-storage/-/random-access-storage-1.4.3.tgz";
        sha512 = "D5e2iIC5dNENWyBxsjhEnNOMCwZZ64TARK6dyMN+3g4OTC4MJxyjh9hKLjTGoNhDOPrgjI+YlFEHFnrp/cSnzQ==";
      };
    };
    "random-iterate-1.0.1" = {
      name = "random-iterate";
      packageName = "random-iterate";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/random-iterate/-/random-iterate-1.0.1.tgz";
        sha512 = "Jdsdnezu913Ot8qgKgSgs63XkAjEsnMcS1z+cC6D6TNXsUXsMxy0RpclF2pzGZTEiTXL9BiArdGTEexcv4nqcA==";
      };
    };
    "randombytes-2.1.0" = {
      name = "randombytes";
      packageName = "randombytes";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/randombytes/-/randombytes-2.1.0.tgz";
        sha512 = "vYl3iOX+4CKUWuxGi9Ukhie6fsqXqS9FE2Zaic4tNFD2N2QQaXOMFbuKK4QmDHC0JO6B1Zp41J0LpT0oR68amQ==";
      };
    };
    "range-parser-1.2.1" = {
      name = "range-parser";
      packageName = "range-parser";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/range-parser/-/range-parser-1.2.1.tgz";
        sha512 = "Hrgsx+orqoygnmhFbKaHE6c296J+HTAQXoxEF6gNupROmmGJRoyzfG3ccAveqCBrwr/2yxQ5BVd/GTl5agOwSg==";
      };
    };
    "range-slice-stream-2.0.0" = {
      name = "range-slice-stream";
      packageName = "range-slice-stream";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/range-slice-stream/-/range-slice-stream-2.0.0.tgz";
        sha512 = "PPYLwZ63lXi6Tv2EZ8w3M4FzC0rVqvxivaOVS8pXSp5FMIHFnvi4MWHL3UdFLhwSy50aNtJsgjY0mBC6oFL26Q==";
      };
    };
    "rc4-0.1.5" = {
      name = "rc4";
      packageName = "rc4";
      version = "0.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/rc4/-/rc4-0.1.5.tgz";
        sha512 = "xdDTNV90z5x5u25Oc871Xnvu7yAr4tV7Eluh0VSvrhUkry39q1k+zkz7xroqHbRq+8PiazySHJPArqifUvz9VA==";
      };
    };
    "readable-stream-2.3.7" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.3.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.3.7.tgz";
        sha512 = "Ebho8K4jIbHAxnuxi7o42OrZgF/ZTNcsZj6nRKyUmkhLFq8CHItp/fy6hQZuZmP/n3yZ9VBUbp4zz/mX8hmYPw==";
      };
    };
    "readable-stream-3.6.0" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "3.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-3.6.0.tgz";
        sha512 = "BViHy7LKeTz4oNnkcLJ+lVSL6vpiFeX6/d3oSH8zCW7UxP2onchk+vTGB143xuFjHS3deTgkKoXXymXqymiIdA==";
      };
    };
    "record-cache-1.2.0" = {
      name = "record-cache";
      packageName = "record-cache";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/record-cache/-/record-cache-1.2.0.tgz";
        sha512 = "kyy3HWCez2WrotaL3O4fTn0rsIdfRKOdQQcEJ9KpvmKmbffKVvwsloX063EgRUlpJIXHiDQFhJcTbZequ2uTZw==";
      };
    };
    "render-media-4.1.0" = {
      name = "render-media";
      packageName = "render-media";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/render-media/-/render-media-4.1.0.tgz";
        sha512 = "F5BMWDmgATEoyPCtKjmGNTGN1ghoZlfRQ3MJh8dS/MrvIUIxupiof/Y9uahChipXcqQ57twVbgMmyQmuO1vokw==";
      };
    };
    "require-directory-2.1.1" = {
      name = "require-directory";
      packageName = "require-directory";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/require-directory/-/require-directory-2.1.1.tgz";
        sha512 = "fGxEI7+wsG9xrvdjsrlmL22OMTTiHRwAMroiEeMgq8gzoLC/PQr7RsRDSTLUg/bZAZtF+TVIkHc6/4RIKrui+Q==";
      };
    };
    "restore-cursor-3.1.0" = {
      name = "restore-cursor";
      packageName = "restore-cursor";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/restore-cursor/-/restore-cursor-3.1.0.tgz";
        sha512 = "l+sSefzHpj5qimhFSE5a8nufZYAM3sBSVMAPtYkmC+4EH2anSGaEMXSD0izRQbu9nfyQ9y5JrVmp7E8oZrUjvA==";
      };
    };
    "rimraf-3.0.2" = {
      name = "rimraf";
      packageName = "rimraf";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/rimraf/-/rimraf-3.0.2.tgz";
        sha512 = "JZkJMZkAGFFPP2YqXZXPbMlMBgsxzE8ILs4lMIX/2o0L9UBw9O/Y3o6wFw/i9YLapcUJWwqbi3kdxIPdC62TIA==";
      };
    };
    "run-async-2.4.1" = {
      name = "run-async";
      packageName = "run-async";
      version = "2.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/run-async/-/run-async-2.4.1.tgz";
        sha512 = "tvVnVv01b8c1RrA6Ep7JkStj85Guv/YrMcwqYQnwjsAS2cTmmPGBBjAjpCW7RrSodNSoE2/qg9O4bceNvUuDgQ==";
      };
    };
    "run-parallel-1.2.0" = {
      name = "run-parallel";
      packageName = "run-parallel";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/run-parallel/-/run-parallel-1.2.0.tgz";
        sha512 = "5l4VyZR86LZ/lDxZTR6jqL8AFE2S0IFLMP26AbjsLVADxHdhB/c0GUsH+y39UfCi3dzz8OlQuPmnaJOMoDHQBA==";
      };
    };
    "run-parallel-limit-1.1.0" = {
      name = "run-parallel-limit";
      packageName = "run-parallel-limit";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/run-parallel-limit/-/run-parallel-limit-1.1.0.tgz";
        sha512 = "jJA7irRNM91jaKc3Hcl1npHsFLOXOoTkPCUL1JEa1R82O2miplXXRaGdjW/KM/98YQWDhJLiSs793CnXfblJUw==";
      };
    };
    "run-series-1.1.9" = {
      name = "run-series";
      packageName = "run-series";
      version = "1.1.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/run-series/-/run-series-1.1.9.tgz";
        sha512 = "Arc4hUN896vjkqCYrUXquBFtRZdv1PfLbTYP71efP6butxyQ0kWpiNJyAgsxscmQg1cqvHY32/UCBzXedTpU2g==";
      };
    };
    "rusha-0.8.14" = {
      name = "rusha";
      packageName = "rusha";
      version = "0.8.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/rusha/-/rusha-0.8.14.tgz";
        sha512 = "cLgakCUf6PedEu15t8kbsjnwIFFR2D4RfL+W3iWFJ4iac7z4B0ZI8fxy4R3J956kAI68HclCFGL8MPoUVC3qVA==";
      };
    };
    "rxjs-7.5.5" = {
      name = "rxjs";
      packageName = "rxjs";
      version = "7.5.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/rxjs/-/rxjs-7.5.5.tgz";
        sha512 = "sy+H0pQofO95VDmFLzyaw9xNJU4KTRSwQIGM6+iG3SypAtCiLDzpeG8sJrNCWn2Up9km+KhkvTdbkrdy+yzZdw==";
      };
    };
    "safe-buffer-5.1.2" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.2.tgz";
        sha512 = "Gd2UZBJDkXlY7GbJxfsE8/nvKkUEU1G38c1siN6QP6a9PT9MmHB8GnpscSmMJSoF8LOIrt8ud/wPtojys4G6+g==";
      };
    };
    "safe-buffer-5.2.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.2.1.tgz";
        sha512 = "rp3So07KcdmmKbGvgaNxQSJr7bGVSVk5S9Eq1F+ppbRo70+YeaDxkw5Dd8NPN+GD6bjnYm2VuPuCXmpuYvmCXQ==";
      };
    };
    "safer-buffer-2.1.2" = {
      name = "safer-buffer";
      packageName = "safer-buffer";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
        sha512 = "YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==";
      };
    };
    "sax-1.1.4" = {
      name = "sax";
      packageName = "sax";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/sax/-/sax-1.1.4.tgz";
        sha512 = "5f3k2PbGGp+YtKJjOItpg3P99IMD84E4HOvcfleTb5joCHNXYLsR9yWFPOYGgaeMPDubQILTCMdsFb2OMeOjtg==";
      };
    };
    "signal-exit-3.0.7" = {
      name = "signal-exit";
      packageName = "signal-exit";
      version = "3.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/signal-exit/-/signal-exit-3.0.7.tgz";
        sha512 = "wnD2ZE+l+SPC/uoS0vXeE9L1+0wuaMqKlfz9AMUo38JsyLSBWSFcHR1Rri62LZc12vLr1gb3jl7iwQhgwpAbGQ==";
      };
    };
    "simple-concat-1.0.1" = {
      name = "simple-concat";
      packageName = "simple-concat";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/simple-concat/-/simple-concat-1.0.1.tgz";
        sha512 = "cSFtAPtRhljv69IK0hTVZQ+OfE9nePi/rtJmw5UjHeVyVroEqJXP1sFztKUy1qU+xvz3u/sfYJLa947b7nAN2Q==";
      };
    };
    "simple-get-2.8.2" = {
      name = "simple-get";
      packageName = "simple-get";
      version = "2.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/simple-get/-/simple-get-2.8.2.tgz";
        sha512 = "Ijd/rV5o+mSBBs4F/x9oDPtTx9Zb6X9brmnXvMW4J7IR15ngi9q5xxqWBKU744jTZiaXtxaPL7uHG6vtN8kUkw==";
      };
    };
    "simple-get-4.0.1" = {
      name = "simple-get";
      packageName = "simple-get";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/simple-get/-/simple-get-4.0.1.tgz";
        sha512 = "brv7p5WgH0jmQJr1ZDDfKDOSeWWg+OVypG99A/5vYGPqJ6pxiaHLy8nxtFjBA7oMa01ebA9gfh1uMCFqOuXxvA==";
      };
    };
    "simple-peer-9.11.1" = {
      name = "simple-peer";
      packageName = "simple-peer";
      version = "9.11.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/simple-peer/-/simple-peer-9.11.1.tgz";
        sha512 = "D1SaWpOW8afq1CZGWB8xTfrT3FekjQmPValrqncJMX7QFl8YwhrPTZvMCANLtgBwwdS+7zURyqxDDEmY558tTw==";
      };
    };
    "simple-sha1-3.1.0" = {
      name = "simple-sha1";
      packageName = "simple-sha1";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/simple-sha1/-/simple-sha1-3.1.0.tgz";
        sha512 = "ArTptMRC1v08H8ihPD6l0wesKvMfF9e8XL5rIHPanI7kGOsSsbY514MwVu6X1PITHCTB2F08zB7cyEbfc4wQjg==";
      };
    };
    "simple-websocket-9.1.0" = {
      name = "simple-websocket";
      packageName = "simple-websocket";
      version = "9.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/simple-websocket/-/simple-websocket-9.1.0.tgz";
        sha512 = "8MJPnjRN6A8UCp1I+H/dSFyjwJhp6wta4hsVRhjf8w9qBHRzxYt14RaOcjvQnhD1N4yKOddEjflwMnQM4VtXjQ==";
      };
    };
    "smart-buffer-4.2.0" = {
      name = "smart-buffer";
      packageName = "smart-buffer";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/smart-buffer/-/smart-buffer-4.2.0.tgz";
        sha512 = "94hK0Hh8rPqQl2xXc3HsaBoOXKV20MToPkcXvwbISWLEs+64sBq5kFgn2kJDHb1Pry9yrP0dxrCI9RRci7RXKg==";
      };
    };
    "socks-2.6.2" = {
      name = "socks";
      packageName = "socks";
      version = "2.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/socks/-/socks-2.6.2.tgz";
        sha512 = "zDZhHhZRY9PxRruRMR7kMhnf3I8hDs4S3f9RecfnGxvcBHQcKcIH/oUcEWffsfl1XxdYlA7nnlGbbTvPz9D8gA==";
      };
    };
    "speed-limiter-1.0.2" = {
      name = "speed-limiter";
      packageName = "speed-limiter";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/speed-limiter/-/speed-limiter-1.0.2.tgz";
        sha512 = "Ax+TbUOho84bWUc3AKqWtkIvAIVws7d6QI4oJkgH4yQ5Yil+lR3vjd/7qd51dHKGzS5bFxg0++QwyNRN7s6rZA==";
      };
    };
    "speedometer-1.1.0" = {
      name = "speedometer";
      packageName = "speedometer";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/speedometer/-/speedometer-1.1.0.tgz";
        sha512 = "z/wAiTESw2XVPssY2XRcme4niTc4S5FkkJ4gknudtVoc33Zil8TdTxHy5torRcgqMqksJV2Yz8HQcvtbsnw0mQ==";
      };
    };
    "split-1.0.1" = {
      name = "split";
      packageName = "split";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/split/-/split-1.0.1.tgz";
        sha512 = "mTyOoPbrivtXnwnIxZRFYRrPNtEFKlpB2fvjSnCQUiAA6qAZzqwna5envK4uk6OIeP17CsdF3rSBGYVBsU0Tkg==";
      };
    };
    "stream-to-blob-2.0.1" = {
      name = "stream-to-blob";
      packageName = "stream-to-blob";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-to-blob/-/stream-to-blob-2.0.1.tgz";
        sha512 = "GXlqXt3svqwIVWoICenix5Poxi4KbCF0BdXXUbpU1X4vq1V8wmjiEIU3aFJzCGNFpKxfbnG0uoowS3nKUgSPYg==";
      };
    };
    "stream-to-blob-url-3.0.2" = {
      name = "stream-to-blob-url";
      packageName = "stream-to-blob-url";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-to-blob-url/-/stream-to-blob-url-3.0.2.tgz";
        sha512 = "PS6wT2ZyyR38Cy+lE6PBEI1ZmO2HdzZoLeDGG0zZbYikCZd0dh8FUoSeFzgWLItpBYw1WJmPVRLpykRV+lAWLQ==";
      };
    };
    "stream-with-known-length-to-buffer-1.0.4" = {
      name = "stream-with-known-length-to-buffer";
      packageName = "stream-with-known-length-to-buffer";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-with-known-length-to-buffer/-/stream-with-known-length-to-buffer-1.0.4.tgz";
        sha512 = "ztP79ug6S+I7td0Nd2GBeIKCm+vA54c+e60FY87metz5n/l6ydPELd2lxsljz8OpIhsRM9HkIiAwz85+S5G5/A==";
      };
    };
    "streamx-2.12.4" = {
      name = "streamx";
      packageName = "streamx";
      version = "2.12.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/streamx/-/streamx-2.12.4.tgz";
        sha512 = "K3xdIp8YSkvbdI0PrCcP0JkniN8cPCyeKlcZgRFSl1o1xKINCYM93FryvTSOY57x73pz5/AjO5B8b9BYf21wWw==";
      };
    };
    "string-width-4.2.3" = {
      name = "string-width";
      packageName = "string-width";
      version = "4.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-4.2.3.tgz";
        sha512 = "wKyQRQpjJ0sIp62ErSZdGsjMJWsap5oRNihHhu6G7JVO/9jIB6UyevL+tXuOqrng8j/cxKTWyWUwvSTriiZz/g==";
      };
    };
    "string2compact-1.3.2" = {
      name = "string2compact";
      packageName = "string2compact";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/string2compact/-/string2compact-1.3.2.tgz";
        sha512 = "3XUxUgwhj7Eqh2djae35QHZZT4mN3fsO7kagZhSGmhhlrQagVvWSFuuFIWnpxFS0CdTB2PlQcaL16RDi14I8uw==";
      };
    };
    "string_decoder-1.1.1" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.1.1.tgz";
        sha512 = "n/ShnvDi6FHbbVfviro+WojiFzv+s8MPMHBczVePfUpDJLwoLT0ht1l4YwBCbi8pJAveEEdnkHyPyTP/mzRfwg==";
      };
    };
    "string_decoder-1.3.0" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.3.0.tgz";
        sha512 = "hkRX8U1WjJFd8LsDJ2yQ/wWWxaopEsABU1XfkM8A+j0+85JAGppt16cr1Whg6KIbb4okU6Mql6BOj+uup/wKeA==";
      };
    };
    "strip-ansi-6.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-6.0.1.tgz";
        sha512 = "Y38VPSHcqkFrCpFnQ9vuSXmquuv5oXOKpGeT6aGrr3o3Gc9AlVa6JBfUSOCnbxGGZF+/0ooI7KrPuUSztUdU5A==";
      };
    };
    "supports-color-7.2.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-7.2.0.tgz";
        sha512 = "qpCAvRl9stuOHveKsn7HncJRvv501qIacKzQlO/+Lwxc9+0q2wLyv4Dfvt80/DPn2pqOBsJdDiogXGR9+OvwRw==";
      };
    };
    "thirty-two-1.0.2" = {
      name = "thirty-two";
      packageName = "thirty-two";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/thirty-two/-/thirty-two-1.0.2.tgz";
        sha1 = "4ca2fffc02a51290d2744b9e3f557693ca6b627a";
      };
    };
    "through-2.3.8" = {
      name = "through";
      packageName = "through";
      version = "2.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/through/-/through-2.3.8.tgz";
        sha1 = "0dd4c9ffaabc357960b1b724115d7e0e86a2e1f5";
      };
    };
    "throughput-1.0.1" = {
      name = "throughput";
      packageName = "throughput";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/throughput/-/throughput-1.0.1.tgz";
        sha512 = "4Mvv5P4xyVz6RM07wS3tGyZ/kPAiKtLeqznq3hK4pxDiTUSyQ5xeFlBiWxflCWexvSnxo2aAfedzKajJqihz4Q==";
      };
    };
    "thunky-0.1.0" = {
      name = "thunky";
      packageName = "thunky";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/thunky/-/thunky-0.1.0.tgz";
        sha1 = "bf30146824e2b6e67b0f2d7a4ac8beb26908684e";
      };
    };
    "thunky-1.1.0" = {
      name = "thunky";
      packageName = "thunky";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/thunky/-/thunky-1.1.0.tgz";
        sha512 = "eHY7nBftgThBqOyHGVN+l8gF0BucP09fMo0oO/Lb0w1OF80dJv+lDVpXG60WMQvkcxAkNybKsrEIE3ZtKGmPrA==";
      };
    };
    "tmp-0.0.33" = {
      name = "tmp";
      packageName = "tmp";
      version = "0.0.33";
      src = fetchurl {
        url = "https://registry.npmjs.org/tmp/-/tmp-0.0.33.tgz";
        sha512 = "jRCJlojKnZ3addtTOjdIqoRuPEKBvNXcGYqzO6zWZX8KfKEpnGY5jfggJQ3EjKuu8D4bJRr0y+cYJFmYbImXGw==";
      };
    };
    "to-arraybuffer-1.0.1" = {
      name = "to-arraybuffer";
      packageName = "to-arraybuffer";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-arraybuffer/-/to-arraybuffer-1.0.1.tgz";
        sha1 = "7d229b1fcc637e466ca081180836a7aabff83f43";
      };
    };
    "torrent-discovery-9.4.12" = {
      name = "torrent-discovery";
      packageName = "torrent-discovery";
      version = "9.4.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/torrent-discovery/-/torrent-discovery-9.4.12.tgz";
        sha512 = "Des49BZggopAXc/rF8+MqDd4NGe9iwT4g7LGzithHUYocTax5wFFnVXkUh6N5U9sGZN4RZ1dr7bVIkD3xCfxIA==";
      };
    };
    "torrent-piece-2.0.1" = {
      name = "torrent-piece";
      packageName = "torrent-piece";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/torrent-piece/-/torrent-piece-2.0.1.tgz";
        sha512 = "JLSOyvQVLI6JTWqioY4vFL0JkEUKQcaHQsU3loxkCvPTSttw8ePs2tFwsP4XIjw99Fz8EdOzt/4faykcbnPbCQ==";
      };
    };
    "tslib-2.4.0" = {
      name = "tslib";
      packageName = "tslib";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tslib/-/tslib-2.4.0.tgz";
        sha512 = "d6xOpEDfsi2CZVlPQzGeux8XMwLT9hssAsaPYExaQMuYskwb+x1x7J371tWlbBdWHroy99KnVB6qIkUbs5X3UQ==";
      };
    };
    "type-fest-0.21.3" = {
      name = "type-fest";
      packageName = "type-fest";
      version = "0.21.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-fest/-/type-fest-0.21.3.tgz";
        sha512 = "t0rzBq87m3fVcduHDUFhKmyyX+9eo6WQjZvf51Ea/M0Q7+T374Jp1aUiyUl0GKxp8M/OETVHSDvmkyPgvX+X2w==";
      };
    };
    "typedarray-0.0.6" = {
      name = "typedarray";
      packageName = "typedarray";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/typedarray/-/typedarray-0.0.6.tgz";
        sha1 = "867ac74e3864187b1d3d47d996a78ec5c8830777";
      };
    };
    "typedarray-to-buffer-3.1.5" = {
      name = "typedarray-to-buffer";
      packageName = "typedarray-to-buffer";
      version = "3.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/typedarray-to-buffer/-/typedarray-to-buffer-3.1.5.tgz";
        sha512 = "zdu8XMNEDepKKR+XYOXAVPtWui0ly0NtohUscw+UmaHiAWT8hrV1rr//H6V+0DvJ3OQ19S979M0laLfX8rm82Q==";
      };
    };
    "uint64be-2.0.2" = {
      name = "uint64be";
      packageName = "uint64be";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/uint64be/-/uint64be-2.0.2.tgz";
        sha512 = "9QqdvpGQTXgxthP+lY4e/gIBy+RuqcBaC6JVwT5I3bDLgT/btL6twZMR0pI3/Fgah9G/pdwzIprE5gL6v9UvyQ==";
      };
    };
    "unordered-array-remove-1.0.2" = {
      name = "unordered-array-remove";
      packageName = "unordered-array-remove";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/unordered-array-remove/-/unordered-array-remove-1.0.2.tgz";
        sha1 = "c546e8f88e317a0cf2644c97ecb57dba66d250ef";
      };
    };
    "upnp-device-client-1.0.2" = {
      name = "upnp-device-client";
      packageName = "upnp-device-client";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/upnp-device-client/-/upnp-device-client-1.0.2.tgz";
        sha1 = "91f84705f2349bf89082855fff4e3006ac435337";
      };
    };
    "upnp-mediarenderer-client-1.4.0" = {
      name = "upnp-mediarenderer-client";
      packageName = "upnp-mediarenderer-client";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/upnp-mediarenderer-client/-/upnp-mediarenderer-client-1.4.0.tgz";
        sha512 = "F+C3Yceoz0j3ZWEchz5tpaOEqkbpObRUmeuPGc9+2u2YvC1CDbXGQ6mjbM10MDhnUJ0tTWYTufpj6xsWctnULw==";
      };
    };
    "url-join-4.0.1" = {
      name = "url-join";
      packageName = "url-join";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/url-join/-/url-join-4.0.1.tgz";
        sha512 = "jk1+QP6ZJqyOiuEI9AEWQfju/nB2Pw466kbA0LEZljHwKeMgd9WrAEgEGxjPDD2+TNbbb37rTyhEfrCXfuKXnA==";
      };
    };
    "ut_metadata-3.5.2" = {
      name = "ut_metadata";
      packageName = "ut_metadata";
      version = "3.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ut_metadata/-/ut_metadata-3.5.2.tgz";
        sha512 = "3XZZuJSeoIUyMYSuDbTbVtP4KAVGHPfU8nmHFkr8LJc+THCaUXwnu/2AV+LCSLarET/hL9IlbNfYTGrt6fOVuQ==";
      };
    };
    "ut_pex-3.0.2" = {
      name = "ut_pex";
      packageName = "ut_pex";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ut_pex/-/ut_pex-3.0.2.tgz";
        sha512 = "3xM88t+AVU5GR0sIY3tmRMLUS+YKiwStc7U7+ZFQ+UHQpX7BjVJOomhmtm0Bs+8R2n812Dt2ymXm01EqDrOOpQ==";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "videostream-3.2.2" = {
      name = "videostream";
      packageName = "videostream";
      version = "3.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/videostream/-/videostream-3.2.2.tgz";
        sha512 = "4tz23yGGeATmbzj/ZnUm6wgQ4E1lzmMXu2mUA/c0G6adtWKxm1Di5YejdZdRsK6SdkLjKjhplFFYT7r+UUDKvA==";
      };
    };
    "vlc-command-1.2.0" = {
      name = "vlc-command";
      packageName = "vlc-command";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vlc-command/-/vlc-command-1.2.0.tgz";
        sha512 = "YTr1w5KmxRN5CBCvplKOD6g/OjwCl5iz+SIjDbq8gWTkByYZun5duHm+OLUkBlbJrCGvMyFyNhTMQxV4Ny0v8g==";
      };
    };
    "wcwidth-1.0.1" = {
      name = "wcwidth";
      packageName = "wcwidth";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/wcwidth/-/wcwidth-1.0.1.tgz";
        sha1 = "f0b0dcf915bc5ff1528afadb2c0e17b532da2fe8";
      };
    };
    "webtorrent-1.8.22" = {
      name = "webtorrent";
      packageName = "webtorrent";
      version = "1.8.22";
      src = fetchurl {
        url = "https://registry.npmjs.org/webtorrent/-/webtorrent-1.8.22.tgz";
        sha512 = "gJv4RBpas5L5KyDvhq4HpHgnwdwKQtqBEkDAgqGzSVqq74DY5/9yz3Y+YdnddmlDh3WKlInOXRfIYRR9ZyaRXg==";
      };
    };
    "webtorrent-cli-4.1.0" = {
      name = "webtorrent-cli";
      packageName = "webtorrent-cli";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/webtorrent-cli/-/webtorrent-cli-4.1.0.tgz";
        sha512 = "H0cQTp+GiyeasRKdpo3SUGoMJzM5NRnBSR/FhUwfY3COK9aTRVzv/+EWmdyilBzjbEro2F2gxIucLqz693JcMg==";
      };
    };
    "winreg-1.2.4" = {
      name = "winreg";
      packageName = "winreg";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/winreg/-/winreg-1.2.4.tgz";
        sha1 = "ba065629b7a925130e15779108cf540990e98d1b";
      };
    };
    "wrap-ansi-7.0.0" = {
      name = "wrap-ansi";
      packageName = "wrap-ansi";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrap-ansi/-/wrap-ansi-7.0.0.tgz";
        sha512 = "YVGIj2kamLSTxw6NsZjoBxfSwsn0ycdesmc4p+Q21c5zPuZ1pl+NfxVdxPtdHvmNVOQ6XSYG4AUtyt/Fi7D16Q==";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "ws-7.5.8" = {
      name = "ws";
      packageName = "ws";
      version = "7.5.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-7.5.8.tgz";
        sha512 = "ri1Id1WinAX5Jqn9HejiGb8crfRio0Qgu8+MtL36rlTA6RLsMdWt1Az/19A2Qij6uSHUMphEFaTKa4WG+UNHNw==";
      };
    };
    "xml2js-0.4.23" = {
      name = "xml2js";
      packageName = "xml2js";
      version = "0.4.23";
      src = fetchurl {
        url = "https://registry.npmjs.org/xml2js/-/xml2js-0.4.23.tgz";
        sha512 = "ySPiMjM0+pLDftHgXY4By0uswI3SPKLDw/i3UXbnO8M/p28zqexCUoPmQFrYD+/1BzhGJSs2i1ERWKJAtiLrug==";
      };
    };
    "xmlbuilder-11.0.1" = {
      name = "xmlbuilder";
      packageName = "xmlbuilder";
      version = "11.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/xmlbuilder/-/xmlbuilder-11.0.1.tgz";
        sha512 = "fDlsI/kFEx7gLvbecc0/ohLG50fugQp8ryHzMTuW9vSa1GJ0XYWKnhsUx7oie3G98+r56aTQIUB4kht42R3JvA==";
      };
    };
    "y18n-5.0.8" = {
      name = "y18n";
      packageName = "y18n";
      version = "5.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/y18n/-/y18n-5.0.8.tgz";
        sha512 = "0pfFzegeDWJHJIAmTLRP2DwHjdF5s7jo9tuztdQxAhINCdvS+3nGINqPd00AphqJR/0LhANUS6/+7SCb98YOfA==";
      };
    };
    "yargs-17.5.1" = {
      name = "yargs";
      packageName = "yargs";
      version = "17.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/yargs/-/yargs-17.5.1.tgz";
        sha512 = "t6YAJcxDkNX7NFYiVtKvWUz8l+PaKTLiL63mJYWR2GnHq2gjEWISzsLp9wg3aY36dY1j+gfIEL3pIF+XlJJfbA==";
      };
    };
    "yargs-parser-21.0.1" = {
      name = "yargs-parser";
      packageName = "yargs-parser";
      version = "21.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/yargs-parser/-/yargs-parser-21.0.1.tgz";
        sha512 = "9BK1jFpLzJROCI5TzwZL/TU4gqjK5xiHV/RfWLOahrjAko/e4DJkRDZQXfvqAsiZzzYhgAzbgz6lg48jcm4GLg==";
      };
    };
  };
  args = {
    name = "webtorrent-cli";
    packageName = "webtorrent-cli";
    version = "4.1.0";
    src = ./.;
    dependencies = [
      sources."@webtorrent/http-node-1.3.0"
      sources."addr-to-ip-port-1.5.4"
      sources."ansi-escapes-4.3.2"
      sources."ansi-regex-5.0.1"
      sources."ansi-styles-4.3.0"
      sources."b4a-1.5.3"
      sources."balanced-match-1.0.2"
      sources."base64-js-1.5.1"
      sources."bencode-2.0.3"
      sources."bep53-range-1.1.1"
      sources."binary-search-1.3.6"
      sources."bitfield-4.1.0"
      (sources."bittorrent-dht-10.0.4" // {
        dependencies = [
          sources."debug-4.3.4"
          sources."ms-2.1.2"
        ];
      })
      (sources."bittorrent-lsd-1.1.1" // {
        dependencies = [
          sources."debug-4.3.4"
          sources."ms-2.1.2"
        ];
      })
      sources."bittorrent-peerid-1.3.4"
      (sources."bittorrent-protocol-3.5.5" // {
        dependencies = [
          sources."debug-4.3.4"
          sources."ms-2.1.2"
        ];
      })
      (sources."bittorrent-tracker-9.19.0" // {
        dependencies = [
          sources."clone-2.1.2"
          sources."debug-4.3.4"
          sources."decompress-response-6.0.0"
          sources."mimic-response-3.1.0"
          sources."ms-2.1.2"
          sources."simple-get-4.0.1"
        ];
      })
      sources."bl-4.1.0"
      sources."blob-to-buffer-1.2.9"
      sources."block-stream2-2.1.0"
      sources."bn.js-5.2.1"
      sources."brace-expansion-1.1.11"
      sources."browserify-package-json-1.0.1"
      sources."buffer-5.7.1"
      sources."buffer-alloc-1.2.0"
      sources."buffer-alloc-unsafe-1.1.0"
      sources."buffer-fill-1.0.0"
      sources."buffer-from-1.1.2"
      sources."cache-chunk-store-3.2.2"
      sources."chalk-4.1.2"
      sources."chardet-0.7.0"
      sources."charset-1.0.1"
      sources."chrome-dgram-3.0.6"
      sources."chrome-dns-1.0.1"
      sources."chrome-net-3.3.4"
      sources."chunk-store-stream-4.3.0"
      sources."cli-cursor-3.1.0"
      sources."cli-spinners-2.6.1"
      sources."cli-width-3.0.0"
      sources."cliui-7.0.4"
      sources."clone-1.0.4"
      sources."color-convert-2.0.1"
      sources."color-name-1.1.4"
      sources."common-tags-1.8.2"
      sources."compact2string-1.4.1"
      sources."concat-map-0.0.1"
      (sources."concat-stream-1.6.2" // {
        dependencies = [
          sources."readable-stream-2.3.7"
          sources."safe-buffer-5.1.2"
          sources."string_decoder-1.1.1"
        ];
      })
      sources."core-util-is-1.0.3"
      sources."cpus-1.0.3"
      sources."create-torrent-5.0.2"
      sources."debug-2.6.9"
      sources."decompress-response-3.3.0"
      sources."defaults-1.0.3"
      sources."define-lazy-prop-2.0.0"
      (sources."dlnacasts-0.1.0" // {
        dependencies = [
          sources."mime-1.6.0"
        ];
      })
      (sources."ecstatic-4.1.4" // {
        dependencies = [
          sources."mime-2.6.0"
        ];
      })
      sources."ee-first-1.1.1"
      sources."elementtree-0.1.7"
      sources."emoji-regex-8.0.0"
      sources."end-of-stream-1.4.4"
      sources."err-code-3.0.1"
      sources."escalade-3.1.1"
      sources."escape-html-1.0.3"
      sources."escape-string-regexp-1.0.5"
      sources."events-3.3.0"
      sources."external-editor-3.1.0"
      sources."fast-fifo-1.1.0"
      sources."figures-3.2.0"
      sources."filestream-5.0.0"
      sources."freelist-1.0.3"
      (sources."fs-chunk-store-2.0.5" // {
        dependencies = [
          sources."thunky-1.1.0"
        ];
      })
      sources."fs.realpath-1.0.0"
      sources."get-browser-rtc-1.1.0"
      sources."get-caller-file-2.0.5"
      sources."get-stdin-8.0.0"
      sources."glob-7.2.3"
      sources."has-flag-4.0.0"
      sources."he-1.2.0"
      sources."http-parser-js-0.4.13"
      sources."iconv-lite-0.4.24"
      sources."ieee754-1.2.1"
      sources."immediate-chunk-store-2.2.0"
      sources."inflight-1.0.6"
      sources."inherits-2.0.4"
      sources."inquirer-8.2.4"
      sources."ip-1.1.8"
      sources."ip-set-2.1.0"
      sources."ipaddr.js-2.0.1"
      sources."is-ascii-1.0.0"
      sources."is-docker-2.2.1"
      sources."is-file-1.0.0"
      sources."is-fullwidth-code-point-3.0.0"
      sources."is-interactive-1.0.0"
      sources."is-typedarray-1.0.0"
      sources."is-unicode-supported-0.1.0"
      sources."is-wsl-2.2.0"
      sources."isarray-1.0.0"
      sources."junk-3.1.0"
      sources."k-bucket-5.1.0"
      sources."k-rpc-5.1.0"
      sources."k-rpc-socket-1.11.1"
      sources."last-one-wins-1.0.4"
      sources."limiter-1.1.5"
      (sources."load-ip-set-2.2.1" // {
        dependencies = [
          sources."decompress-response-6.0.0"
          sources."mimic-response-3.1.0"
          sources."simple-get-4.0.1"
        ];
      })
      sources."lodash-4.17.21"
      sources."log-symbols-4.1.0"
      sources."lru-3.1.0"
      (sources."lt_donthave-1.0.1" // {
        dependencies = [
          sources."debug-4.3.4"
          sources."ms-2.1.2"
        ];
      })
      sources."magnet-uri-6.2.0"
      sources."mediasource-2.4.0"
      sources."memory-chunk-store-1.3.5"
      sources."mime-3.0.0"
      sources."mimic-fn-2.1.0"
      sources."mimic-response-1.0.1"
      sources."minimatch-3.1.2"
      sources."minimist-1.2.6"
      sources."mkdirp-classic-0.5.3"
      sources."moment-2.29.3"
      sources."mp4-box-encoding-1.4.1"
      sources."mp4-stream-3.1.3"
      sources."ms-2.0.0"
      sources."multistream-4.1.0"
      sources."mute-stream-0.0.8"
      sources."netmask-2.0.2"
      sources."network-address-1.1.2"
      sources."next-event-1.0.0"
      sources."node-ssdp-2.9.1"
      sources."on-finished-2.4.1"
      sources."once-1.4.0"
      sources."onetime-5.1.2"
      sources."open-8.4.0"
      sources."ora-5.4.1"
      sources."os-tmpdir-1.0.2"
      sources."package-json-versionify-1.0.4"
      (sources."parse-torrent-9.1.5" // {
        dependencies = [
          sources."decompress-response-6.0.0"
          sources."mimic-response-3.1.0"
          sources."simple-get-4.0.1"
        ];
      })
      sources."path-is-absolute-1.0.1"
      sources."piece-length-2.0.1"
      sources."prettier-bytes-1.0.4"
      sources."process-nextick-args-2.0.1"
      sources."pump-3.0.0"
      sources."queue-microtask-1.2.3"
      sources."queue-tick-1.0.0"
      sources."random-access-file-2.2.1"
      sources."random-access-storage-1.4.3"
      sources."random-iterate-1.0.1"
      sources."randombytes-2.1.0"
      sources."range-parser-1.2.1"
      sources."range-slice-stream-2.0.0"
      sources."rc4-0.1.5"
      sources."readable-stream-3.6.0"
      sources."record-cache-1.2.0"
      (sources."render-media-4.1.0" // {
        dependencies = [
          sources."debug-4.3.4"
          sources."ms-2.1.2"
        ];
      })
      sources."require-directory-2.1.1"
      sources."restore-cursor-3.1.0"
      sources."rimraf-3.0.2"
      sources."run-async-2.4.1"
      sources."run-parallel-1.2.0"
      sources."run-parallel-limit-1.1.0"
      sources."run-series-1.1.9"
      sources."rusha-0.8.14"
      sources."rxjs-7.5.5"
      sources."safe-buffer-5.2.1"
      sources."safer-buffer-2.1.2"
      sources."sax-1.1.4"
      sources."signal-exit-3.0.7"
      sources."simple-concat-1.0.1"
      sources."simple-get-2.8.2"
      (sources."simple-peer-9.11.1" // {
        dependencies = [
          sources."buffer-6.0.3"
          sources."debug-4.3.4"
          sources."ms-2.1.2"
        ];
      })
      sources."simple-sha1-3.1.0"
      (sources."simple-websocket-9.1.0" // {
        dependencies = [
          sources."debug-4.3.4"
          sources."ms-2.1.2"
        ];
      })
      sources."smart-buffer-4.2.0"
      sources."socks-2.6.2"
      sources."speed-limiter-1.0.2"
      sources."speedometer-1.1.0"
      sources."split-1.0.1"
      sources."stream-to-blob-2.0.1"
      sources."stream-to-blob-url-3.0.2"
      sources."stream-with-known-length-to-buffer-1.0.4"
      sources."streamx-2.12.4"
      sources."string-width-4.2.3"
      sources."string2compact-1.3.2"
      sources."string_decoder-1.3.0"
      sources."strip-ansi-6.0.1"
      sources."supports-color-7.2.0"
      sources."thirty-two-1.0.2"
      sources."through-2.3.8"
      sources."throughput-1.0.1"
      sources."thunky-0.1.0"
      sources."tmp-0.0.33"
      sources."to-arraybuffer-1.0.1"
      (sources."torrent-discovery-9.4.12" // {
        dependencies = [
          sources."debug-4.3.4"
          sources."ms-2.1.2"
        ];
      })
      sources."torrent-piece-2.0.1"
      sources."tslib-2.4.0"
      sources."type-fest-0.21.3"
      sources."typedarray-0.0.6"
      sources."typedarray-to-buffer-3.1.5"
      sources."uint64be-2.0.2"
      sources."unordered-array-remove-1.0.2"
      sources."upnp-device-client-1.0.2"
      sources."upnp-mediarenderer-client-1.4.0"
      sources."url-join-4.0.1"
      (sources."ut_metadata-3.5.2" // {
        dependencies = [
          sources."debug-4.3.4"
          sources."ms-2.1.2"
        ];
      })
      sources."ut_pex-3.0.2"
      sources."util-deprecate-1.0.2"
      sources."videostream-3.2.2"
      sources."vlc-command-1.2.0"
      sources."wcwidth-1.0.1"
      (sources."webtorrent-1.8.22" // {
        dependencies = [
          sources."debug-4.3.4"
          sources."decompress-response-6.0.0"
          sources."mimic-response-3.1.0"
          sources."ms-2.1.2"
          sources."simple-get-4.0.1"
        ];
      })
      sources."webtorrent-cli-4.1.0"
      sources."winreg-1.2.4"
      sources."wrap-ansi-7.0.0"
      sources."wrappy-1.0.2"
      sources."ws-7.5.8"
      sources."xml2js-0.4.23"
      sources."xmlbuilder-11.0.1"
      sources."y18n-5.0.8"
      sources."yargs-17.5.1"
      sources."yargs-parser-21.0.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
