# This file has been generated by node2nix 1.8.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "now-18.0.0" = {
      name = "now";
      packageName = "now";
      version = "18.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/now/-/now-18.0.0.tgz";
        sha512 = "MVskFV3xH1hMkpTewPCb3p0SQ17hL7EI1Zb+Ij2wYiRV3X0a6G91GdE2vvFlhsK6rhRHKHZnDQkZ0AnkpnfzHA==";
      };
    };
  };
  args = {
    name = "now";
    packageName = "now";
    version = "18.0.0";
    src = ./.;
    dependencies = [
      sources."now-18.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}