# This file has been generated by node2nix 1.8.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "now-19.0.0" = {
      name = "now";
      packageName = "now";
      version = "19.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/now/-/now-19.0.0.tgz";
        sha512 = "UdDMAGMI1rfjM9AF8QaJDlst3W7v/CMjlK9uiB4H6CX396ynxeLNes5YW3gXYT4FLqxI64/AAN+SFgOQ2rW2uw==";
      };
    };
  };
  args = {
    name = "now";
    packageName = "now";
    version = "19.0.0";
    src = ./.;
    dependencies = [
      sources."now-19.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}